### ISSUE TITLE
AttributeError: 'CrossAttention' object has no attribute 'lora_layer_name'

### ISSUE THREAD

**Issue by jowbester** [hako-mikan/sd-webui-regional-prompter#107]
Using this version: e203fc0f (Wed May 10 11:00:37 2023)
I get the following error message:

Error completing request
Arguments: ('task(n4dxgpnve1i6mcw)', 'a man and a woman, a man with black hair\nBREAK\na man and a woman, a woman with blonde hair', 'disfigured, deformed, ugly', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, <controlnet.py.UiControlNetUnit object at 0x000002AE1F24FA90>, <controlnet.py.UiControlNetUnit object at 0x000002AE09A300A0>, True, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 145, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 97, in forward
    if not self.calced and "diffusion_model_output_blocks_11_1_transformer_blocks_0_attn2" == module.lora_layer_name:
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CrossAttention' object has no attribute 'lora_layer_name'

I just wanted to follow this guide https://stable-diffusion-art.com/regional-prompter/ to get started with this addon.
Is this a know issue I just wasn't able to find here or is it specific to me? Any ideas for a possible fix? Thanks in advance!

Edit.: Only when the Generation Mode is on "Attention". Let me know, if u need anymore informatio

**Comment by Symbiomatrix** [comment]
Try to comment out these two lines in attention.py, line 97:
```
        if not self.calced and "diffusion_model_output_blocks_11_1_transformer_blocks_0_attn2" == module.lora_layer_name:
            self.calced = True
```
They don't seem to serve any purpose within the extension, and I can't see .calced in my webui version either.
I can only imagine it's something unusual in the checkpoint or webui version you're using, since I've never encountered a module which doesn't have a layer name, so other errors might still occur elsewhere.

**Comment by jowbester** [comment]
It works now, thank you. I tried it with different checkpoints and never used a lora. Just using it in auto1111. Other extensions are imho very basic stuff like controlnet, dreambooth and ultimate upscale. 

Nevertheless, its fixed :) Thank you!

**Comment by Symbiomatrix** [comment]
@jowbester Hold on, you mean that it had the same error even with other checkpoints, until commenting?
I don't have dreambooth or ultimate upscale, but if it might potentially be causing problems I'll have a PR remove these lines as well.

**Comment by jowbester** [comment]
Yes, tried a bunch of the "most used" checkpoints or rather the safetensor files.

**Comment by jowbester** [comment]
Also now, when creating a random image without regional prompting, I get this error message:

Error running postprocess: A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 403, in postprocess
    unloader(self, p)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 423, in unloader
    unloadlorafowards(p)
  File "A:\AI Stuff\automatic1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 491, in unloadlorafowards
    import lora
ModuleNotFoundError: No module named 'lora'

**Comment by Symbiomatrix** [comment]
When did you install webui? When was the last time you updated it?
There should be a file in webui/extensions-builtin/Lora called lora.py. If there isn't, you might have a very old version that won't work properly.

**Comment by jowbester** [comment]
I usually keep it up to date and the last complete reinstall was before 2 weeks. Also I do have this file.

**Comment by Symbiomatrix** [comment]
Sorry, I don't really know what the suggest. I think the lora imports can safety be moved to the beginning of the file instead of spread out in all of latent's functions, but I'm not sure that'd help. Locon has a similar "import lora", and I've never heard of such an issue before. Locally I might be able to debug that with some effort (path issue, namespace), but remotely I'm insufficiently experienced with the repo and import shenanigans.
