### ISSUE TITLE
AttributeError: 'list' object has no attribute 'upper'

### ISSUE THREAD

**Issue by kakaruYH03** [hako-mikan/sd-webui-regional-prompter#137]
<img width="450" alt="스크린샷 2023-06-02 163906" src="https://github.com/hako-mikan/sd-webui-regional-prompter/assets/54255373/e06d7746-8016-4e91-a27f-ed8eb3797317">

```
postprocess_image :  0 0 ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, '] ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, ']
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 14.27it/s]
Error running process: E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py0, 17.24it/s]
Traceback (most recent call last):
  File "E:\WEBUI\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 385, in process
    self, p = flagfromkeys(self, p)
  File "E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 960, in flagfromkeys
    if KEYPROMPT in p.prompt.upper():
AttributeError: 'list' object has no attribute 'upper'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.42it/s]
postprocess_image :  0 0 ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, '] ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, ']
```
debug Check off

```
postprocess_image :  0 0 ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, '] ['2girls, city BREAK\nyellow eyes, green hair, BREAK\nred eyes, black hair, ']
mode : Attention
divide : Horizontal
usebase : False
base ratios : []
usecommon : True
usenegcom : False
use 2D : False
Error running postprocess: E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "E:\WEBUI\stable-diffusion-webui\modules\scripts.py", line 478, in postprocess
    script.postprocess(p, processed, *script_args)
  File "E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 509, in postprocess
    if self.debug : debugall(self)
  File "E:\WEBUI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 941, in debugall
    print(f"divide : {self.divide}\neq : {self.eq}\n")
AttributeError: 'Script' object has no attribute 'eq'
```
debug Check ON

version: v1.3.1-RC-6-gb6af0a38  •  python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: 0.0.19  •  gradio: 3.31.0  

When active is checked
Extension does not work with error

Generation mode
Same when checking Latent

**Comment by hako-mikan** [comment]
I couldnt reproduce your error.
Maybe fixed.
Did you use multiple prompt or any extension?
