### ISSUE TITLE
Latent + LoRA producing error

### ISSUE THREAD

**Issue by mdlieber99** [hako-mikan/sd-webui-regional-prompter#148]
Thanks for your help on my previous two issues.  I'm still trying to apply two LoRAs to different segments of the screen (left and right).  I have fine-tuned my own models and then extracted the LoRA's which work fine in general.  I ran the following prompt in attention model and it worked fine:

glamour magazine portrait of 2women looking at viewer, official balmain editorial, dramatic lighting highly detailed, analog photo, overglaze, 80mm Sigma f/1.4 <lora:Anna:1> BREAK blond woman BREAK red haired woman

As expected it applied the look of the lora model to both women.  But when I switched to latent mode (and left the prompt exactly the same) I get the following error:

RuntimeError: The size of tensor a (96) must match the size of tensor b (94) at non-singleton dimension 3

Any ideas for how to fix this?

**Comment by Symbiomatrix** [comment]
What is this, common or base? You should probably apply the lora to each region rather than common.
Need to see all settings and full error log, I cannot guess what you have done or how the program responded based on clues, I'm no holmes.

**Comment by mdlieber99** [comment]
Sure - the prompt when I did it with a lora in each regions was as follows:

portrait of women BREAK portrait of a woman's face, slightly reddish hair  <lora:Anna:1> BREAK portrait of a woman's face, blond hair <lora:Polina:1>

The error is:  RuntimeError: The size of tensor a (88) must match the size of tensor b (86) at non-singleton dimension 3

Here is the log:

Error completing request
Arguments: ('task(gqsb38sgmvvkzqp)', "portrait of women BREAK portrait of a woman's face, slightly reddish hair  <lora:Anna:1> BREAK portrait of a woman's face, blond hair <lora:Polina:1>", '', [], 50, 0, False, False, 1, 1, 5.5, -1.0, -1.0, 0, 0, 0, False, 704, 704, True, 0.35, 1.7, 'Lanczos', 0, 0, 0, 0, '', '', [], 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <controlnet.py.UiControlNetUnit object at 0x7f333933abf0>, True, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, True, False, 'Latent', False, '0', '0', '0.4', None, False, False, 'Denoised', 5.0, 0.0, 0.0, 'Standard operation', 'mp4', 'h264', 2.0, 0.0, 0.0, False, 0.0, True, True, False, False, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 728, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 976, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 383, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 383, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 143, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 82, in forward
    x = layer(x, emb)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 249, in forward
    return checkpoint(
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 262, in _forward
    h = self.in_layers(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 476, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 399, in lora_forward
    res = res + module.up(module.down(x)) * scale
RuntimeError: The size of tensor a (88) must match the size of tensor b (86) at non-singleton dimension 3


![Untitled](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/105756477/ac6dc168-56fc-46d1-8e55-5e835dfe8fc4)

I also get the same error if I leave the mask at default at 512 x 512 or match the image size  at and put the mask at 704 x 704.  Otherwise I did not touch the settings in mask or prompt parts of "regional prompter"

Here is the main prompt settings:

![Untitled2](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/105756477/5f59aa29-8d32-4791-bbe0-4c77b1b8364d)

**Comment by Symbiomatrix** [comment]
Have you tried running without hires fix? It's been having multiple stability issues since the method was altered on webui V1.3, hako introduced a fix but it might be insufficient. Other than that I'm seeing nothing out of the ordinary.

**Comment by mdlieber99** [comment]
ok - so good news and bad news.  the good news - its works wit hires off (sort of) and then it turns out it works with hires on as long as the final hires resolution is also divisible by 8.  However it even when it works, it is just blending the two lora's together.  I get a mix of the two unique faces from each lora that shows up in each face.  That is, each lora gets applied to the whole image even though they are in separate BREAK sections.  Any more thoughts on this?  I created a bunch of images and it was consistently applying both lora's to both faces (and still did this with hires off)

**Comment by Symbiomatrix** [comment]
Yeah, I know that feeling, loras have been a pain to separate for a long time. Assuming you're still on latent mode, and it's generating two people on either side of the image, then it's possibly another thing that broke on the recent version. In the [known issues section](https://github.com/hako-mikan/sd-webui-regional-prompter#known-issues) I've posted a sample of how the separation should be / was working.
Perhaps you could try a couple of popular loras and see if the same thing happens?
