### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Davikar** [hako-mikan/sd-webui-regional-prompter#160]
```
06:44:33-733402 ERROR    Running script process:
                         C:\AI\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py: AttributeError
╭─────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮
│ C:\AI\automatic\modules\scripts.py:406 in process                                                               │
│                                                                                                                 │
│   405 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                  │
│ ❱ 406 │   │   │   │   script.process(p, *args, **kwargs)                                                        │
│   407 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                 │
│                                                                                                                 │
│ C:\AI\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:348 in process                              │
│                                                                                                                 │
│    347 │   │   │   unloader(self,p)                                                                             │
│ ❱  348 │   │   │   self.unloader(p)                                                                             │
│    349 │   │   │   # Fsr, if self.all are emptied in init and extension is on,                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Script' object has no attribute 'unloader'
```

Getting this error now after the latest updates. (Regional Prompter extension isn't even enabled)

**Comment by AugmentedRealityCat** [comment]
I have a similar error message and I have the feeling both of our problems are related. I was not using the extension either, and this shows up each time I generate an image.
```
*** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py:00, 23.93it/s]
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 348, in process
        self.unloader(p)
    AttributeError: 'Script' object has no attribute 'unloader'
```

**Comment by ccbruce0812** [comment]
I have the same problem after a git pull.
Now the problem persists even though the extension is disabled.

*** Error running process: E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 348, in process
        self.unloader(p)
    AttributeError: 'Script' object has no attribute 'unloader'

---

**Comment by liulsg** [comment]
I have the same problem

**Comment by theddr** [comment]
> I have the same problem

the same problem,I have rollback 5f0681e

**Comment by hako-mikan** [comment]
fixed, thanks.

**Comment by Symbiomatrix** [comment]
Missed a comment marker, sorry 'bout that.
