### ISSUE TITLE
'Network' object has no attribute 'multiplier'

### ISSUE THREAD

**Issue by NightShadow1910** [hako-mikan/sd-webui-regional-prompter#173]
*** Error running process_batch: Z:\UI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "Z:\UI\stable-diffusion-webui\modules\scripts.py", line 519, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "Z:\UI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 443, in process_batch
        lora_namer(self, p, lnter, lnur)
      File "Z:\UI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 194, in lora_namer
        ldict[lora.name] = lora.multiplier
    AttributeError: 'Network' object has no attribute 'multiplier'
    
    Got this error after trying to use a Lora with the extension. Been using the lora in the common section and the settings are good i think.
    
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/77676301/f3df0dba-31d6-4b86-b6d3-f7a8fb641ccc)

**Comment by hako-mikan** [comment]
May be fixed.
