### ISSUE TITLE
The Scrpits can`t run in the 'Attention' mode

### ISSUE THREAD

**Issue by ling0403** [hako-mikan/sd-webui-regional-prompter#174]
Well I have to say It is very strange because **It run very well yesterday**.But since I upgrated some other extensions,this error happens:

    Traceback (most recent call last):
      File "G:\ai-paint\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "G:\ai-paint\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "G:\ai-paint\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "G:\ai-paint\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "G:\ai-paint\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "G:\ai-paint\modules\processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "G:\ai-paint\modules\processing.py", line 992, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "G:\ai-paint\modules\sd_samplers_kdiffusion.py", line 439, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "G:\ai-paint\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "G:\ai-paint\modules\sd_samplers_kdiffusion.py", line 439, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\py\venv\webui\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "G:\ai-paint\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\modules\sd_samplers_kdiffusion.py", line 164, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "G:\ai-paint\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "G:\ai-paint\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "G:\ai-paint\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1572, in _call_impl
        result = forward_call(*args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "D:\py\venv\webui\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "G:\ai-paint\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
        x = self.attn2(self.norm2(x), context=context) + x
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1522, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\py\venv\webui\lib\site-packages\torch\nn\modules\module.py", line 1531, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\attention.py", line 347, in forward
        if self.eq:
    AttributeError: 'Script' object has no attribute 'eq'

version: [v1.4.1]•  python: 3.10.11  •  torch: 2.1.0.dev20230716+cu121  •  xformers: 0.0.21+c979299.d20230718  •  gradio: 3.32.0

**I have tried to reinstall the extension,but nothing changes.Hope to get your reply as soon as possible,Thanks！

**Comment by ling0403** [comment]
OK.It`s fixed after I downgrade the extension to a86d786

**Comment by hako-mikan** [comment]
To say that you got that error,
It is very likely that there was another error before that one.
It would be great if you could tell us about that one.

**Comment by hako-mikan** [comment]
To say that you got that error,
It is very likely that there was another error before that one.
It would be great if you could tell me about that one.

**Comment by dolce1211** [comment]
I had exactly the same error.
I believe the error took place before the one mentioned is below;


`Error running process: K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "K:\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 412, in process
    neighbor(self,p)                                                            #detect other extention
  File "K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 611, in neighbor
    if key in args:
  File "K:\stable-diffusion-webui\venv\lib\site-packages\pandas\core\generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`


The error above shows up in both Attention and Latent mode, but the process stops only when I am using Attention mode.

**Comment by ling0403** [comment]
This is exactly the error abrove,kinda similar with mine

> I had exactly the same error. I believe the error took place before the one mentioned is below;
> 
> `Error running process: K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py Traceback (most recent call last): File "K:\stable-diffusion-webui\modules\scripts.py", line 451, in process script.process(p, *script_args) File "K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 412, in process neighbor(self,p) #detect other extention File "K:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 611, in neighbor if key in args: File "K:\stable-diffusion-webui\venv\lib\site-packages\pandas\core\generic.py", line 1527, in __nonzero__ raise ValueError( ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`
> 
> The error above shows up in both Attention and Latent mode, but the process stops only when I am using Attention mode.

**Mine would be like this** 
*** Error running process: G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "G:\ai-paint\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\rp.py", line 412, in process
        neighbor(self,p)                                                            #detect other extention
      File "G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\rp.py", line 611, in neighbor
        if key in args:
      File "D:\py\venv\webui\lib\site-packages\pandas\core\generic.py", line 1466, in __nonzero__
        raise ValueError(
    ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by ling0403** [comment]
I am glad it start running again,but I got a piece of error code in the console like:
```
*** Error running process_batch: G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "G:\ai-paint\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "G:\ai-paint\extensions\sd-webui-regional-prompter\scripts\rp.py", line 437, in process_batch
        p.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size] = self.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size]
    AttributeError: 'Script' object has no attribute 'all_prompts'
```

**but it will not affect normal use**

> by the way,  my webui is the master branch as far as I konw,

**Comment by hako-mikan** [comment]
thanks reporting.
maybe fixed.
