### ISSUE TITLE
UnboundLocalError: local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [hako-mikan/sd-webui-regional-prompter#179]
attention, prompt

It *does* seem to work, though. Maps are generated, images are generated according to maps too.

Regional Prompter Active, Pos tokens : [65, 34], Neg tokens : [38]
  0% 0/20 [00:00<?, ?it/s]Error executing callback cfg_denoiser_callback for /content/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/script_callbacks.py", line 193, in cfg_denoiser_callback
    c.callback(params)
  File "/content/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 473, in denoiser_callback
    denoiser_callback_s(self, params)
  File "/content/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 119, in denoiser_callback_s
    att.pmasksf[key] = allmask
UnboundLocalError: local variable 'key' referenced before assignment

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
