### ISSUE TITLE
How to safely call unloader() from another extension?

### ISSUE THREAD

**Issue by ThereforeGames** [hako-mikan/sd-webui-regional-prompter#188]
Hi,

Some context: I'm working on improving the compatibility between Regional Prompter and my extension, Unprompted. My extension can append tasks such as img2img to the main processing loop, but I need to disable Regional Prompter before engaging those tasks in order to prevent errors.

The way I'm doing this now is by importing the `rp.py` file and calling its `unloader()` method like so:

```
if script_title == "regional prompter" and script.active:
	rp_path = self.Unprompted.extension_path("sd-webui-regional-prompter")
	rp_mod = self.Unprompted.import_file(f"sd-webui-regional-prompter.scripts.rp", f"{rp_path}/scripts/rp.py")
	rp_mod.unloader(script, self.Unprompted.p_copy)
	self.log.debug("Successfully unloaded Regional Prompter")
```

However, importing `rp.py` is problematic as it throws an error related to the `reload()` statements:

```
2023-07-29 21:47:29,956 - Unprompted - ERROR - An error ocurred while trying to bypass an extension: regional prompterTraceback (most recent call last):
  File "T:\code\python\automatic-stable-diffusion-webui\extensions\_unprompted/shortcodes\basic\after.py", line 38, in after
    rp_mod = self.Unprompted.import_file(f"sd-webui-regional-prompter.scripts.rp", f"{rp_path}/scripts/rp.py")
  File "T:\code\python\automatic-stable-diffusion-webui\extensions\_unprompted\lib_unprompted\shared.py", line 409, in import_file
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "T:\code\python\automatic-stable-diffusion-webui\extensions\sd-webui-regional-prompter/scripts/rp.py", line 16, in <module>
    reload(scripts.regions)  # update without restarting web-ui.bat
  File "T:\programs\anaconda3\lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'scripts.regions'
```

If I wrap lines 15-17 in a try/catch block, Regional Prompter seems to unload correctly. But maybe there is a more sensible way to go about this? The `unloader()` method isn't part of the Script object, so I don't think I can call it directly.

Would appreciate your thoughts on this. Thanks!

**Comment by hako-mikan** [comment]
For now, I made it so that there are no errors, but I'm not sure if it works properly.
