### ISSUE TITLE
AttributeError: 'Script' object has no attribute 'isbefore15'

### ISSUE THREAD

**Issue by Array-Cats** [hako-mikan/sd-webui-regional-prompter#194]
update to commit c1c6418-commit af1b884 show error in t2i (i2i not to test)。

commit cc21973 maybe normal

err info
```
---
	Tile 1/9
	Tile 2/9
	Tile 3/9
	Tile 4/9
	Tile 5/9
	Tile 6/9
	Tile 7/9
	Tile 8/9
	Tile 9/9
*** Error running before_hr: W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 616, in before_hr
        script.before_hr(p, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 440, in before_hr
        lora_namer(self, p, lnter, lnur)
      File "W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 216, in lora_namer
        ldict_u[lora.name] =lora.multiplier if self.isbefore15 else lora.unet_multiplier
    AttributeError: 'Script' object has no attribute 'isbefore15'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

```

**Comment by hako-mikan** [comment]
Are there any errors before this error?

**Comment by Array-Cats** [comment]
> Are there any errors before this error?

No.... This is full info
```
Python 3.10.12 (main, Jun  8 2023, 17:32:40) [MSC v.1936 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

loading WD14-tagger reqs from W:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Launching Web UI with arguments: --theme dark --port 65500 --xformers --opt-channelslast --api
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: W:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: Set Proxy: http://127.0.0.1:8084
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.7.11, num models: 13
dirname:  W:\stable-diffusion-webui\localizations
localizations:  {'I18N_sd-webui-zh_CN': 'W:\\stable-diffusion-webui\\localizations\\I18N_sd-webui-zh_CN.json', '简体中文语言包_StormyOrange': 'W:\\stable-diffusion-webui\\extensions\\SD-WebUI-Localization_ZH_CN\\localizations\\简体中文语言包_StormyOrange.json'}
2023-08-04 19:46:01,946 - ControlNet - INFO - ControlNet v1.1.234
ControlNet preprocessor location: W:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-04 19:46:02,064 - ControlNet - INFO - ControlNet v1.1.234
== WD14 tagger gpu, uname_result(system='Windows', node='FlyingCats-PC', release='10', version='10.0.22621', machine='AMD64') ==
Loading weights [54ef3e3610] from W:\stable-diffusion-webui\models\Stable-diffusion\C\2D\meinamix_meinaV11.safetensors
Creating model from config: W:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:65500

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 27.1s (launcher: 5.9s, import torch: 5.1s, import gradio: 0.7s, setup paths: 0.5s, other imports: 0.8s, list SD models: 1.2s, load scripts: 10.9s, create ui: 1.3s, gradio launch: 0.3s, add APIs: 0.3s).
Loading VAE weights specified in settings: W:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 6.1s (load weights from disk: 0.9s, create model: 1.2s, apply weights to model: 1.0s, apply channels_last: 0.5s, apply half(): 0.7s, load VAE: 0.8s, move model to device: 0.7s, calculate empty prompt: 0.2s).
	Tile 1/9
	Tile 2/9
	Tile 3/9
	Tile 4/9
	Tile 5/9
	Tile 6/9
	Tile 7/9
	Tile 8/9
	Tile 9/9
*** Error running before_hr: W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 616, in before_hr
        script.before_hr(p, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 440, in before_hr
        lora_namer(self, p, lnter, lnur)
      File "W:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 216, in lora_namer
        ldict_u[lora.name] =lora.multiplier if self.isbefore15 else lora.unet_multiplier
    AttributeError: 'Script' object has no attribute 'isbefore15'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
```

**Comment by hako-mikan** [comment]
Ok, I got it.
You met error when this extension is not active, right?
If so, fixed.

**Comment by Array-Cats** [comment]
> Ok, I got it. You met error when this extension is not active, right? If so, fixed.

Good, THX
