### ISSUE TITLE
Error completing request:10, 4.21s/it]

### ISSUE THREAD

**Issue by WBV-CWB** [hako-mikan/sd-webui-regional-prompter#201]
I'm having this error in the final process, does anyone know anything about it?

My configuration is :

Ryzen 5600g/ 32ram/nvme 1tb and RTX 2060 6gb

EEROR:

Error completing request:10, 4.21s/it]

Arguments: ('task(2usbkdkmg6fey87)', '2girls \nBREAK <lora:TakagiV:1>, takagi1, long hair, brown eyes, brown hair, forehead, small breasts \nBREAK <lora:houjou_takagisan_v2:1>, houjou_takagisan, short hair, hairclip, brown eyes, brown hair, forehead, small breasts,', 'easynegative, ng_deepnegative_v1_75t, verybadimagenegative_v1.3, 2koma, 3koma, multiple_views,\n', [], 30, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 768, 768, False, 0.55, 1.25, 'R-ESRGAN 4x+ Anime6B', 20, 0, 0, 0, '', '', [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, 960, 64, True, True, True, False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000024D52B87670>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000024D52AB9D50>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000024D52ABB490>, [], [], False, 4, 0, 0.8, 0, 0.8, 0.5, False, True, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', True, True, False, 'Latent', False, '0.1,0.1,', '0.1,0.1,', '0.4', None, '0', '0', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}

Traceback (most recent call last):

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\call_[queue.py](http://queue.py/)", line 57, in f

res = list(func(*args, **kwargs))

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\call_[queue.py](http://queue.py/)", line 37, in f

res = func(*args, **kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[txt2img.py](http://txt2img.py/)", line 57, in txt2img

processed = processing.process_images(p)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[processing.py](http://processing.py/)", line 610, in process_images

res = process_images_inner(p)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\extensions\sd-webui-controlnet-main\scripts\batch_[hijack.py](http://hijack.py/)", line 42, in processing_process_images_hijack

return getattr(processing, '__controlnet_original_process_images_inner')(p, args, *kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[processing.py](http://processing.py/)", line 730, in process_images_inner

x_samples_ddim = [decode_first_stage([p.sd](http://p.sd/)_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[processing.py](http://processing.py/)", line 730, in <listcomp>

x_samples_ddim = [decode_first_stage([p.sd](http://p.sd/)_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[processing.py](http://processing.py/)", line 518, in decode_first_stage

x = model.decode_first_stage(x)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\sd_hijack_[utils.py](http://utils.py/)", line 17, in <lambda>

setattr(resolved_obj, func_path[-1], lambda args, *kwargs: self(*args, **kwargs))

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\sd_hijack_[utils.py](http://utils.py/)", line 26, in call

return self.__sub_func(self.__orig_func, args, *kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\sd_hijack_[unet.py](http://unet.py/)", line 76, in <lambda>

first_stage_sub = lambda orig_func, self, x, kwargs: orig_func(self, [x.to](http://x.to/)(devices.dtype_vae), kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_[contextlib.py](http://contextlib.py/)", line 115, in decorate_context

return func(*args, **kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\[ddpm.py](http://ddpm.py/)", line 826, in decode_first_stage

return self.first_stage_model.decode(z)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\modules\[lowvram.py](http://lowvram.py/)", line 52, in first_stage_model_decode_wrap

return first_stage_model_decode(z)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\[autoencoder.py](http://autoencoder.py/)", line 89, in decode

z = [self.post](http://self.post/)_quant_conv(z)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](http://module.py/)", line 1501, in callimpl

return forward_call(*args, **kwargs)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\extensions-builtin\Lora\[lora.py](http://lora.py/)", line 411, in lora_Conv2d_forward

return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\extensions-builtin\Lora\[lora.py](http://lora.py/)", line 373, in lora_forward

res = original_forward(module, input)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[conv.py](http://conv.py/)", line 463, in forward

return self._conv_forward(input, self.weight, self.bias)

File "C:\Users\Documents\sd_telegram\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[conv.py](http://conv.py/)", line 459, in convforward

return F.conv2d(input, weight, bias, self.stride,

RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

Could you help me?

**Comment by hako-mikan** [comment]
Is this issue still occurring? If so, please provide details about your environment.
The startup options might be related.
