### ISSUE TITLE
script has no attribute 'all_prompts'

### ISSUE THREAD

**Issue by Xeltosh** [hako-mikan/sd-webui-regional-prompter#202]
since today i get this line of error.

*** Error running process: C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 374, in process
        self.all_prompts = p.all_prompts.copy()
    AttributeError: 'tuple' object has no attribute 'copy'

---
*** Error running before_process_batch: C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\modules\scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 444, in before_process_batch
        self.current_prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'

---
*** Error running process_batch: C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\modules\scripts.py", line 543, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 471, in process_batch
        p.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size] = self.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size]
    AttributeError: 'Script' object has no attribute 'all_prompts'

this error show itself as such:
- i set a batch-count of 2 and a batch-size of 2 and i get instead 4 batches of 2 pics
- i set a batch-count of 1 and a batch-size of 4 and i get instead 4 batches of 4 pics
- i set a batch-count of 4 and a batch-size of 1 and i get instead 16 batches of 1 pic

and it even affects other extensions, as the "dynamic prompts". The randomizer-function only works on batches now, instead of each picture like before.

**Comment by DHKnight8628** [comment]
I get the same error.
It worked fine yesterday, but these anomalies appear today.

**Comment by hako-mikan** [comment]
This script is not updated yesterday.
If you also did not update A1111, maybe other extensions witch updated yesterday is the cause as @Xeltosh  mentioned.

**Comment by MrNeon** [comment]
The issue is with dynamic-prompts itself. Specifically this commit https://github.com/adieyal/sd-dynamic-prompts/commit/638d4b1784b95d19b69c54f93aeee987d2c5b0a2

**Comment by Xeltosh** [comment]
o, and how to rmeedy that?
