### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by DHKnight8628** [hako-mikan/sd-webui-regional-prompter#204]
*** Error running process: E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py", line 374, in process
        self.all_prompts = p.all_prompts.copy()
    AttributeError: 'tuple' object has no attribute 'copy'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running before_process_batch: E:\sd-webui-aki-v4.1\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "E:\sd-webui-aki-v4.1\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 302, in before_process_batch
        prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running before_process_batch: E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py", line 444, in before_process_batch
        self.current_prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process_batch: E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 543, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "E:\sd-webui-aki-v4.1\extensions\sd-webui-regional-prompter\scripts\rp.py", line 471, in process_batch
        p.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size] = self.all_prompts[p.iteration * p.batch_size:(p.iteration + 1) * p.batch_size]
    AttributeError: 'Script' object has no attribute 'all_prompts'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

It worked fine yesterday, but these anomalies appear today.

Help me,please

**Comment by hako-mikan** [comment]
Did you updated dynamic prompt?

**Comment by DHKnight8628** [comment]
yes,i did.
All plugins are up to date.

**Comment by DHKnight8628** [comment]
> 动态提示更新了吗？

yes,i did.
And i stop

**Comment by DHKnight8628** [comment]
> Did you update dynamic prompt?

yes,i did.
And i stop dynamic prompt, regional prompter can be used normally again.
Thank u,bro.
