### ISSUE TITLE
RuntimeError on generation

### ISSUE THREAD

**Issue by Lemniscatas** [hako-mikan/sd-webui-regional-prompter#208]
Hello. I constantly encounter an error when the process reaches Hi.res:
**RuntimeError: shape '[1, 24576, 320]' is invalid for input of size 15728640**

And sometimes, it doesn't even reach Hi.res and gives this error:
**RuntimeError: shape '[1, 6144, 320]' is invalid for input of size 3932160**

I can't figure out what's causing this. I'm using the following prompt:
_`(2girls, a woman and a woman:1.2), 8k, RAW photo, ultra high res, photorealistic, masterpiece, ultra-detailed, Unreal Engine, white background, in the church, <lora:Mild detail adjusterV10_4:1>, wedding dress, off-shoulder, with willow-shaped lace, hair ornament, navel, necklace, collarbone, bare shoulders, bridal gauntlets, gloves, cleavage, elbow gloves, thighs, ADDCOMM photo fullbody alice zuberg, [long ashy hair:long white hair:0.3]:1.2, wild hair, white skin, perfect face, realistic face, seductive posture, seductive smile,looking at viewer, large breast, large ass,perfect body, ({standing|kneeling,spread legs}), naked pussy,  (shirtlift), clothes lift, (cameltoe:1.4), ((detailed nipples)), (running:1.3), (no panties, bottomless, naked pussy, clothes lift:1.3), ADDCOL photo fullbody asuna, (ginger hair, twin braids:1.4), perfect face, realistic face, seductive posture, seductive smile, looking at viewer, large breast, large ass,perfect body, ({standing|kneeling,spread legs}), naked pussy,  (shirtlift), clothes lift, (cameltoe:1.4), ((detailed nipples)), (running:1.3), (no panties, bottomless, naked pussy, clothes lift:1.3), <lora:innievag:0.4>, <lora:asuna:0.3:MIDD>, <lora:alicezubergtest:0.3:MIDD> , <lora:weddingdressex0.3:0.6>,  <lora:shirtliftv3:1>`_ 

And my negative prompt looks like this:
_`ng_deepnegative_v1_75t,easynegative, (bad anatomy, wrong anatomy, amputation), asian, muscular, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), bad anatomy, girl, loli, young,badhandsv5-neg,tattoo, (extra fingers, deformed hands, polydactyl:1.5), (deformed, distorted, disfigured:1.3), poorly drawn, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, (AS-Adult-Neg), ruins, debris, remains, detritus, bag, slit_pussy, (extra legs), (extra hands), clone, wineglass, ((UGLY DEFORMED HANDS))), tattoo, wreck, shivers, carcase, flinders, rubbish, cross-eye, village, country, (malformed hands:1.4), (mutated fingers:1.4), double ass, (text, watermark, signature, autograph, inscriptions:1.5), (legs to the other side), animal ears, beast ears, furry, 3girls:1.4`_

In the plugin itself, it's configured like this:

![111](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/134967230/3ee906d3-6261-4b40-937c-bd548c77e979)

**Sometimes** I use Tiled Vae (but whether I use it or not, the error remains the same). In the query itself, I dynamically use words using Unprompted or dynamic prompt. But even with them disabled, the error occurs.

After running SD, it generates a few outputs, and then I get the error, which doesn't go away except by restarting SD.

Here are my webui-user.bat settings:
```
set PYTHON="C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe"
set GIT=
set VENV_DIR=
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:512
set COMMANDLINE_ARGS=--api --xformers --gradio-img2img-tool color-sketch --administrator --always-batch-cond-uncond --medvram
```
I tried changing --medvram to --lowvram, and even disabling it when using Tiled Vae (I'm using an RTX 3060 6GB with xformer)

Screenshots of additional generation settings:

![333](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/134967230/b06dc57e-8af8-4d14-9393-a5ea4aa0b297)

Error with **RuntimeError: shape '[1, 24576, 320]' is invalid for input of size 15728640** with Debugging in Regional Prompter:
```
torch.Size([1, 64, 48, 320])
torch.Size([1, 64, 48, 320])
output : torch.Size([1, 6144, 320])
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.73it/s]
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]input :  torch.Size([2, 24576, 320])
tokens :  torch.Size([2, 385, 768])
module :  diffusion_model_input_blocks_1_1_transformer_blocks_0_attn2
same token size and different divisions
3 128 192 24576 24576 1024 1536
tokens : [[0, 3], [3, 6]],pn : True
[Outer (0.00:1.00), contains [(0.00:0.50), (0.50:1.00)]
]
tokens : 0-231
 dcell.breaks : 0, dcell.ed : 0.5, dcell.st : 0
0:128,0:96
sumin:64,sumout:0,dsh:128,dsw:192
torch.Size([1, 128, 96, 320])
tokens : 231-462
 dcell.breaks : 0, dcell.ed : 1.0, dcell.st : 0.5
0:128,96:192
sumin:128,sumout:192,dsh:128,dsw:192
torch.Size([1, 128, 96, 320])
torch.Size([1, 128, 96, 320])
3 128 192 24576 24576 1024 1536
tokens : [[0, 4], [4, 5]],pn : False
[Outer (0.00:1.00), contains [(0.00:0.50), (0.50:1.00)]
]
tokens : 0-308
 dcell.breaks : 0, dcell.ed : 0.5, dcell.st : 0
0:128,0:96
sumin:64,sumout:0,dsh:128,dsw:192
torch.Size([1, 128, 96, 320])
tokens : 308-385
 dcell.breaks : 0, dcell.ed : 1.0, dcell.st : 0.5
0:128,96:192
sumin:128,sumout:192,dsh:128,dsw:192
torch.Size([1, 128, 96, 320])
torch.Size([1, 128, 96, 320])
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(rrhx2izxp0ch6ee)', '(2girls, a woman and a woman:1.2), 8k, RAW photo, ultra high res, photorealistic, masterpiece, ultra-detailed, Unreal Engine, white background, in the church, <lora:Mild detail adjusterV10_4:1>, wedding dress, off-shoulder, with willow-shaped lace, hair ornament, navel, necklace, collarbone, bare shoulders, bridal gauntlets, gloves, cleavage, elbow gloves, thighs, ADDCOMM photo fullbody alice zuberg, [long ashy hair:long white hair:0.3]:1.2, wild hair, white skin, perfect face, realistic face, seductive posture, seductive smile,looking at viewer, large breast, large ass,perfect body, ({standing|kneeling,spread legs}), naked pussy,  (shirtlift), clothes lift, (cameltoe:1.4), ((detailed nipples)), (running:1.3), (no panties, bottomless, naked pussy, clothes lift:1.3), ADDCOL photo fullbody asuna, (ginger hair, twin braids:1.4), perfect face, realistic face, seductive posture, seductive smile, looking at viewer, large breast, large ass,perfect body, ({standing|kneeling,spread legs}), naked pussy,  (shirtlift), clothes lift, (cameltoe:1.4), ((detailed nipples)), (running:1.3), (no panties, bottomless, naked pussy, clothes lift:1.3), <lora:innievag:0.4>, <lora:asuna:0.3:MIDD>, <lora:alicezubergtest:0.3:MIDD> , <lora:weddingdressex0.3:0.6>,  <lora:shirtliftv3:1> ', 'ng_deepnegative_v1_75t,easynegative, (bad anatomy, wrong anatomy, amputation), asian, muscular, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), bad anatomy, girl, loli, young,badhandsv5-neg,tattoo, (extra fingers, deformed hands, polydactyl:1.5), (deformed, distorted, disfigured:1.3), poorly drawn, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, (AS-Adult-Neg), ruins, debris, remains, detritus, bag, slit_pussy, (extra legs), (extra hands), clone, wineglass, ((UGLY DEFORMED HANDS))), tattoo, wreck, shivers, carcase, flinders, rubbish, cross-eye, village, country, (malformed hands:1.4), (mutated fingers:1.4), double ass, (text, watermark, signature, autograph, inscriptions:1.5), (legs to the other side), animal ears, beast ears, furry, 3girls:1.4', [], 20, 16, False, False, 1, 1, 6, -1.0, -1.0, 0, 0, 0, False, 512, 768, True, 0.5, 2, '4x-UltraSharp', 10, 0, 0, 0, '', '', [], 0, True, -1.0, True, False, {'ad_model': 'mediapipe_face_full', 'ad_prompt': 'photo fullbody <lora:Wrise_Elsa2:0.6:OUTALL>,  <lora:ports:0.2> 1girl,  [long ashy hair:long white hair:0.3]:1.2, wild hair, white skin, blue eyes, (looking at viewer), realistic face, 8k, RAW photo, ultra high res, photorealistic, masterpiece, ultra-detailed, Unreal Engine, (seductive smile), <lyco:locon_perfecteyes_v1_from_v1_64_32:1.0>, perfecteyes eyes [SEP] photo of <lora:Wrise_Anna:0.5:MIDD> ((1girl)), blush, green eyes, (looking at viewer), realistic face, 8k, RAW photo, ultra high res, photorealistic, masterpiece, ultra-detailed, Unreal Engine, (seductive smile), <lyco:locon_perfecteyes_v1_from_v1_64_32:1.0>, perfecteyes eyes, ', 'ad_negative_prompt': 'EasyNegative:2, cross eye, crossed eyes, (worst quality:2), (low quality:2), (normal quality:2), lowres, poorly drawn, kid, children, child, (blush, pink cheeks, rosy cheeks:1.4), moles, wrinkles, wrinkled skin, cartoon, anime, sketches, (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), (deformed, distorted, disfigured:1.3), poorly drawn, points, defects, stripes, dots, drops, drips, smudges, ink, dirt, stains, spots, (extra eyebrows, eyebrows on the forehead)', 'ad_confidence': 0.1, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 2, 'ad_denoising_strength': 0.5, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'control_v11p_sd15_inpaint [be8bc0ed]', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 960, 64, False, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016F8EF597D0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016F5CB57A10>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016EDFDC6290>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', False, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, True, True, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, True, False, 'Attention', False, '0', '0', '0.4', None, '0', '0', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False) {}
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\processing.py", line 610, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\processing.py", line 728, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\processing.py", line 1058, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
           ^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 137, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
                                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 708, in hacked_basic_transformer_inner_forward
    x = self.attn2(self.norm2(x), context=context) + x
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 399, in forward
    onx = matsepcalc(nx, conn, mask, False, 2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 230, in matsepcalc
    ox = ox.reshape(x.size()[0],x.size()[1],x.size()[2]) # Restore to 3d source.
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 24576, 320]' is invalid for input of size 15728640
```

**What do I need to do to avoid this error? Where did I go wrong?** I would be grateful for any help
P.S. Your plugin works amazingly - it provides the best image results I've ever obtained. And I want to continue using it, but I can't due to these persistent errors.

**Comment by hako-mikan** [comment]
Thanks reporting. May be fixed.
