### ISSUE TITLE
UnboundLocalError: local variable 'ox' referenced before assignment

### ISSUE THREAD

**Issue by s0updev** [hako-mikan/sd-webui-regional-prompter#223]
---
[True,
 True,
 'Nope',
 'Columns',
 'Mask',
 'Prompt',
 '2;3,3,4',
 '0.2',
 True,
 False,
 False,
 'Attention',
 False,
 '0',
 '0',
 '0',
 None,
 '0',
 '0',
 0]
Regional Prompter Active, Pos tokens : [9, 14, 10, 14], Neg tokens : [107]
mode : Nope
calcmode : Attention
usebase : True
base ratios : []
usecommon : False
usenegcom : False
divide : [4, 1]
eq : False
tokens : [9, 14, 10, 14],[107],[[0, 1], [1, 2], [2, 3], [3, 4]],[[0, 2]]
ratios : []

prompt : []
env : before15:False,isxl:True
loras{}
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]input :  torch.Size([1, 4032, 640])
tokens :  torch.Size([1, 308, 2048])
module :  diffusion_model_input_blocks_4_1_transformer_blocks_0_attn2
different tokens size
4 56 72 4032 4032 896 1152
tokens : [[0, 1], [1, 2], [2, 3], [3, 4]],pn : True
[]
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(kgfvlg4j5xt0979)', 'Create a medieval dark fantasy anime-style landscape  ADDBASE \nmysterious misty dead forest in the background, blue sky at night with moon ADDROW \ndepicting a bustling hostile rotten red lands at night ADDCOL\ncomfy faint bonfire as the last hope for the hero to rest in safety', 'castle, fire, burning land', ['Default_Negative'], 20, 'DPM++ 2M Karras', 1, 1, 7, 896, 1152, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000186667C58A0>, 0, False, '', 0.8, 1473554878, False, -1, 0, 0, 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, True, 1, 1, 1, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001864FD121A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001864FD11000>,
<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000186667C5930>, 0, True, True, 'Nope', 'Columns', 'Mask', 'Prompt', '2;3,3,4', '0.2', True, False, False, 'Attention', False, '0', '0', '0', None, '0', '0', 0, False, False, 'positive', 'comma', 0, False, False, '', 7, '<lora:LR1_B1_UNETONLY_10WU-000001:1> ,<lora:LR1_B1_UNETONLY_10WU-000002:1> ,<lora:LR1_B1_UNETONLY_10WU-000003:1> ,<lora:LR1_B1_UNETONLY_10WU-000004:1> ,<lora:LR1_B1_UNETONLY_10WU-000005:1> ,<lora:LR1_B1_UNETONLY_10WU-000006:1> ,<lora:LR1_B1_UNETONLY_10WU-000007:1> ,<lora:LR1_B1_UNETONLY_10WU-000008:1> ,<lora:LR1_B1_UNETONLY_10WU-000009:1> ,<lora:LR1_B1_UNETONLY_10WU-000010:1> ,<lora:LR1_B1_UNETONLY_10WU-000011:1> ,<lora:LR1_B1_UNETONLY_10WU-000012:1> ,<lora:LR1_B1_UNETONLY_10WU-000013:1> ,<lora:LR1_B1_UNETONLY_10WU-000014:1> ,<lora:LR1_B1_UNETONLY_10WU:1>', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing,
'controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "stable-diffusion-webui\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call
        return self.__orig_func(*args, **kwargs)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 993, in forward
        h = module(h, emb, context)
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 100, in forward
x = layer(x, context)
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 627, in forward
        x = block(x, context=context[i])
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 459, in forward
        return checkpoint(
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 165, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 182, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 478, in _forward
        self.attn2(
      File "stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 401, in forward
        ox = matsepcalc(x, contexts, mask, self.pn, 1)
      File "stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 249, in matsepcalc
        ox = ox.reshape(x.size()[0],x.size()[1],x.size()[2]) # Restore to 3d source.
    UnboundLocalError: local variable 'ox' referenced before assignment

---

**Comment by allkhor** [comment]
Same here, revert to 227693ce22af546a65b6c8cf292f4ae13c5ddd73 solve problem.

**Comment by hako-mikan** [comment]
I couldn't reproduce the issue, but I have attempted a fix. Please try it out.

**Comment by s0updev** [comment]
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/47640810/46ee4f88-e615-440e-aa4f-7e4ffc94bae5)
its working now

**Comment by bb7bb** [comment]
> I couldn't reproduce the issue, but I have attempted a fix. Please try it out.

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/26820917/0551d104-c85a-42d1-9a9b-50a19e96961d)

I encountered the same bug, but I found the reason.
@hako-mikan
