### ISSUE TITLE
Latent mode results in NotImplementedError if a Lora is in the prompt

### ISSUE THREAD

**Issue by Kansaku** [hako-mikan/sd-webui-regional-prompter#225]
If i try to use the latent mode and have any Lora in the prompt, hitting generate results in an error.

Tried with SDXL and different Loras.
Automatic1111 Webui Release v1.6
latest Release of this extension

Conole Output:

```shell
   Traceback (most recent call last):
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 668, in sample_dpmpp_3m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 26, in __call__
        return self.__sub_func(self.__orig_func, *args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\sd_hijack_unet.py", line 48, in apply_model
        return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 993, in forward
        h = module(h, emb, context)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 98, in forward
        x = layer(x, emb)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 317, in forward
        return checkpoint(
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 165, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 182, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 329, in _forward
        h = self.in_layers(x)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 440, in network_Conv2d_forward
        return network_forward(self, input, originals.Conv2d_forward)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 413, in network_forward
        y = module.forward(input, y)
      File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 157, in forward
        raise NotImplementedError()
    NotImplementedError
```

**Comment by hako-mikan** [comment]
Please refer to the following example and let me know if you encounter the same error. If so, please provide information about the environment you are using, including launch options and any other extensions you are using simultaneously.
https://github.com/hako-mikan/sd-webui-regional-prompter/issues/221#issuecomment-1731654542

**Comment by Kansaku** [comment]
ok, i have tried the example with success. Latent mode is working with it. After many tries i found out that one specific Lora i tried to use in Latent mode brings up the error. If i dont use it i can generate anything without any errors.
I'm wondering why only this specific Lora is a problem tho. Well its a LoHa to be exact. Could this be the problem?
If you want to recreate the error, here the link to the Lora/LoHa:
[https://civitai.com/models/119275/gothic-doll-sdxl](url)

**Comment by hako-mikan** [comment]
Added option "Use LoHa or other".
With this option, it worked in my environment.
