### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'lora_functional'

### ISSUE THREAD

**Issue by Anon3024** [hako-mikan/sd-webui-regional-prompter#253]
**Describe the bug**
Script will not load upon installation - console out:
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "/home/{user}/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/{user}/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/{user}/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 19, in <module>
        orig_lora_functional = shared.opts.lora_functional
      File "/home/{user}/stable-diffusion-webui/modules/options.py", line 117, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'lora_functional'

**Environment**
Web-UI version: v1.6.0

**Other Enabled Extensions**
stable-diffusion-webui-dataset-tag-editor
LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-options-section
mobile
prompt-bracket-checker

**Comment by DevMerlin** [comment]
Same issue - loaded from the .git url. 

**Environment**
Web-UI version v.1.6.0
python: 3.10.7  •  torch: 2.0.0+cpu

**Other Enabled Extensions**
adetailer
sd-webui-controlnet

All standard built-in

**Comment by hako-mikan** [comment]
probably fixed
