### ISSUE TITLE
An error occurs when using this extension via API - "TypeError: argument of type 'bool' is not iterable"

### ISSUE THREAD

**Issue by waura** [hako-mikan/sd-webui-regional-prompter#257]
**Describe the bug**
An error occurs when using this extension via API.
The request sent to the API is "POST /sdapi/v1/text2img".

The alwayson_scripts of the request is as follow.

```
'alwayson_scripts': {'Regional Prompter': {'args': [True, False, 'Matrix', 'Colums', 'Mask', 'Prompt', '1,1', '0.2', True, True, False, 'Latent', False, '0', '0', '0', '']}},
```

The error is as follow.
```
Oct 21 14:48:48 ubuntu-gpu bash[3792]: *** Error running before_hr: /home/waura/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Oct 21 14:48:48 ubuntu-gpu bash[3792]:     Traceback (most recent call last):
Oct 21 14:48:48 ubuntu-gpu bash[3792]:       File "/home/waura/stable-diffusion-webui/modules/scripts.py", line 730, in before_hr
Oct 21 14:48:48 ubuntu-gpu bash[3792]:         script.before_hr(p, *script_args)
Oct 21 14:48:48 ubuntu-gpu bash[3792]:       File "/home/waura/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 523, in before_hr
Oct 21 14:48:48 ubuntu-gpu bash[3792]:         if "La" in self.calc:
Oct 21 14:48:48 ubuntu-gpu bash[3792]:     TypeError: argument of type 'bool' is not iterable
```

**Environment**
Web-UI version: v1.6.0
LoRA

**Other Enabled Extensions**
- sd-dynamic-prompts

**Comment by chanphillip** [comment]
just got the same issue

**Comment by chanphillip** [comment]
Checked the source code and did some trial and error, I figured out table of the settings is incorrect.

For someone who needs a workaround, you can replace `Not Change AND` with `debug`, and `debug` should be a string instead of boolean.

for @waura example to work:
```
'alwayson_scripts': {'Regional Prompter': {'args': [True, 'Matrix', 'Colums', 'Mask', 'Prompt', '1,1', '0.2', True, True, False, 'Latent', '', '0', '0', '0', '']}},
```

**Comment by hako-mikan** [comment]
Fixed.
Thanks @chanphillip for finding out the cause.

**Comment by waura** [comment]
Thanks. I've confirmed the issue is fixed.
