### ISSUE TITLE
"RuntimeError: shape '[10, 16384]' is invalid for input of size 131072" on hires fix, with resolution a multiple of 8 (SDXL)

### ISSUE THREAD

**Issue by lendrick** [hako-mikan/sd-webui-regional-prompter#262]
I'm running SDXL on the most recent commit of this extension on the most recent automatic1111 official release, and I'm getting an error when I enable hires fix.  My resolution is 1024x1024 and the upscale factor is 2 so both are multiples of 8.  I'm running on a 4090, so vram probably isn't an issue.

Using this prompt here:
asian girl, (dress:1.2), belt, bag, hair, in rainy street, holding umbrella BREAK
(red:1.7), umbrella BREAK
(light green:1.7), dress BREAK
(blond:1.7), hair BREAK
(pink:1.7), belt BREAK
(yellow:1.7), bag
Negative prompt: signature,
Steps: 23, Sampler: DPM++ 2M SDE Karras, CFG scale: 6, Seed: 1, Size: 1024x1024, Model hash: 11ea14fdf8, Model: EnvyBeyondXL01, VAE hash: 235745af8d, VAE: sdxl_vae.safetensors, RP Active: True, RP Divide mode: Prompt, RP Matrix submode: Columns, RP Mask submode: Mask, RP Prompt submode: Prompt-Ex, RP Calc Mode: Attention, RP Ratios: "1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: True, RP Options: [False], RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: 0.7, RP LoRA Stop Step: 0, RP LoRA Hires Stop Step: 0, RP Flip: False, Version: v1.6.0

I get the following error when I enable hires fix:
`
    Traceback (most recent call last):
      File "C:\AI\automatic1111\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\AI\automatic1111\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\AI\automatic1111\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\AI\automatic1111\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\AI\automatic1111\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\AI\automatic1111\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\AI\automatic1111\modules\processing.py", line 1156, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "C:\AI\automatic1111\modules\processing.py", line 1242, in sample_hr_pass
        samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
      File "C:\AI\automatic1111\modules\sd_samplers_kdiffusion.py", line 189, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\AI\automatic1111\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\AI\automatic1111\modules\sd_samplers_kdiffusion.py", line 189, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\AI\automatic1111\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\AI\automatic1111\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\AI\automatic1111\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 993, in forward
        h = module(h, emb, context)
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 100, in forward
        x = layer(x, context)
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\attention.py", line 627, in forward
        x = block(x, context=context[i])
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\attention.py", line 459, in forward
        return checkpoint(
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 165, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 182, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "C:\AI\automatic1111\repositories\generative-models\sgm\modules\attention.py", line 478, in _forward
        self.attn2(
      File "C:\AI\automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\automatic1111\extensions\sd-webui-regional-prompter\scripts\attention.py", line 409, in forward
        ox = promptsepcalc(x, contexts, mask, self.pn, 1)
      File "C:\AI\automatic1111\extensions\sd-webui-regional-prompter\scripts\attention.py", line 352, in promptsepcalc
        out = main_forward(module, x, context, mask, divide, self.isvanilla, userpp = userpp, width = dsw, height = dsh,
      File "C:\AI\automatic1111\extensions\sd-webui-regional-prompter\scripts\attention.py", line 58, in main_forward
        if inhr and not hiresfinished: hiresscaler(height,width,attn)
      File "C:\AI\automatic1111\extensions\sd-webui-regional-prompter\scripts\attention.py", line 531, in hiresscaler
        hiresmask(pmasks,old_h, old_w, new_h, new_w,at = attn[:,:,0])
      File "C:\AI\automatic1111\extensions\sd-webui-regional-prompter\scripts\attention.py", line 545, in hiresmask
        mask = mask.reshape_as(at) if at is not None else mask.reshape(1,mask.shape[1] * mask.shape[2],1)
    RuntimeError: shape '[10, 16384]' is invalid for input of size 131072
`

**Environment**
Web-UI version: 1.6.0
SD Version: SDXL
LoRA/LoCon/LoHa: none

**Other Enabled Extensions**
A bunch.  Is there a good place where I can copy a list from?

**Comment by lendrick** [comment]
Just a note, the same resolution works fine on a 1.5 checkpoint.

**Comment by hako-mikan** [comment]
Fixed.
