### ISSUE TITLE
Object 'Network' has no attribute 'bundle_embeddings'

### ISSUE THREAD

**Issue by obs945** [hako-mikan/sd-webui-regional-prompter#279]
**Describe the bug**
AttributeError: 'Network' object has no attribute 'bundle_embeddings'
After update to the latest version extension, above message appears even regional prompter not activated

**Environment**
Web-UI version: 1.6.0
SD Version: 1.6.0
LoRA/LoCon/LoHa

**Other Enabled Extensions**

*** Error running postprocess: /Volumes/MX500 SSD/stable-diffusion-webui-20230919/extensions/sd-webui-regional-prompter/scripts/rp.py
    Traceback (most recent call last):
      File "/Volumes/MX500 SSD/stable-diffusion-webui-20230919/modules/scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/Volumes/MX500 SSD/stable-diffusion-webui-20230919/extensions/sd-webui-regional-prompter/scripts/rp.py", line 585, in postprocess
        unloader(self, p)
      File "/Volumes/MX500 SSD/stable-diffusion-webui-20230919/extensions/sd-webui-regional-prompter/scripts/rp.py", line 607, in unloader
        unloadlorafowards(p)
      File "/Volumes/MX500 SSD/stable-diffusion-webui-20230919/extensions/sd-webui-regional-prompter/scripts/latent.py", line 568, in unloadlorafowards
        for emb_name, embedding in net.bundle_embeddings.items():
    AttributeError: 'Network' object has no attribute 'bundle_embeddings'

**Comment by hako-mikan** [comment]
Fixed.
