### ISSUE TITLE
Error messages when generating in batch 

### ISSUE THREAD

**Issue by broli** [hako-mikan/sd-webui-regional-prompter#296]
**Describe the bug**
Regional prompter is enabled. Promt is correctly formated
Click generate, works.
Sets batch count to 7, error starts to appear on log

**Environment**
Web-UI version: 1.7.0
SD Version: 1.5
LoRA/LoCon/LoHa: non related

**Other Enabled Extensions**
controlnet opepose

Here is an extract of the log
` 92%|█████████▏| 22/24 [00:39<00:03,  1.81s/it]*** Error executing callback cfg_denoised_callback for /workspace/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py| 334/336 [07:41<00:03,  1.81s/it]
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/script_callbacks.py", line 224, in cfg_denoised_callback
        c.callback(params)
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 591, in denoised_callback
        denoised_callback_s(self, params)
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 194, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range
[mine.log](https://github.com/hako-mikan/sd-webui-regional-prompter/files/14074319/mine.log)
`

**Comment by hackl0r** [comment]
I have a similar issue. 
Regional prompter in img2img works just fine for single images, but since about a month, the batch workflow is broken.
Frist img works fine, just like the non-batch process, but the second image immediatley turns wrong and bleeds into each other (same hair color for example etc.) and continues to become worse with each image.

**Comment by hako-mikan** [comment]
Does this issue still occur with the latest version? 
If so, please provide additional information. 
The number of region divisions, division mode. 
Is it correct to understand that this happens on the 7th calculation when the batch count is set to 7?
