### ISSUE TITLE
Latent mode 'sometimes' not implemented error

### ISSUE THREAD

**Issue by Tesserakt-company** [hako-mikan/sd-webui-regional-prompter#303]
**Describe the bug**
I found the most peculiar bug. I have RegPro working as intended in 'Active' mode. Multiple Loras, Open Pose enable, x/y/z Prompter enabled with different Denoising settings. 
Now I switch to 'Latent' mode and I get an 'Latent mode not implemented' in latent.py.
I switch back to Active mode and I still get the latent not implemented error. 
I disable everything. No Loras, no Controlnet, no Script. Latent works. 
I add loras back, latent works, I add scripts back, latent works. I add Open Pose back, latent works.

WTF

*Error Stack:*
2024-02-25 15:42:28,026 - ControlNet - INFO - unit_separate = False, style_align = False
2024-02-25 15:42:28,026 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_openpose [cab727d4]
2024-02-25 15:42:28,080 - ControlNet - INFO - Using preprocessor: dw_openpose_full
2024-02-25 15:42:28,080 - ControlNet - INFO - preprocessor resolution = 453
2024-02-25 15:42:28,269 - ControlNet - INFO - ControlNet Hooked - Time = 0.24901032447814941
Warning: Nonstandard height / width for ulscaled size
1,1,1,1,1;3,1,1,1,1,1,1,1 0.2 Horizontal
Regional Prompter Active, Pos tokens : [17, 0, 27, 31, 0, 0, 0, 2, 45, 0, 7, 0, 1], Neg tokens : [295]
generating image for xyz plot: NotImplementedError
Traceback (most recent call last):
  File "C:\Users\NAME\stable-diffusion-webui\scripts\xyz_grid.py", line 701, in cell
    res = process_images(pc)
  File "C:\Users\NAME\stable-diffusion-webui\modules\processing.py", line 734, in process_images
    res = process_images_inner(p)
  File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\modules\processing.py", line 857, in process_images_inner
    p.setup_conds()
  File "C:\Users\NAME\stable-diffusion-webui\modules\processing.py", line 1308, in setup_conds
    super().setup_conds()
  File "C:\Users\NAME\stable-diffusion-webui\modules\processing.py", line 469, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
  File "C:\Users\NAME\stable-diffusion-webui\modules\processing.py", line 455, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "C:\Users\NAME\stable-diffusion-webui\modules\prompt_parser.py", line 188, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\NAME\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\NAME\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\NAME\stable-diffusion-webui\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 822, in forward
    return self.text_model(
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 740, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 654, in forward
    layer_outputs = encoder_layer(
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 383, in forward
    hidden_states, attn_weights = self.self_attn(
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 272, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 498, in h_Linear_forward
    return networks.network_forward(self, input, networks.originals.Linear_forward)
  File "C:\Users\NAME\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 469, in network_forward
    y = module.forward(input, y)
  File "C:\Users\NAME\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 158, in forward
    raise NotImplementedError()
NotImplementedError

**Environment**
Web-UI version: 
version: [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2
SD Version: 1.7 I guess
LoRA several Lora, but they don't seem to be issue

**Other Enabled Extensions**
<html><body>

 
--
 

</body>
</html>DWPose 	https://github.com/IDEA-Research/DWPose 	onnx 	[3dca5db7](https://github.com/IDEA-Research/DWPose/commit/3dca5db79d9f9ffdd378753ddf6ec66535aace88) 	2023-12-12 03:54:23 	unknown
TemporalKit 	https://github.com/CiaraStrawberry/TemporalKit 	main 	[f46d255c](https://github.com/CiaraStrawberry/TemporalKit/commit/f46d255cfeb9c4b0c682bae5660a04ac7b7cd8dc) 	2023-10-04 00:10:32 	unknown
sd-webui-controlnet 	https://github.com/Mikubill/sd-webui-controlnet.git 	main 	[679b6279](https://github.com/Mikubill/sd-webui-controlnet/commit/679b62790b22319a6833130c23986fb4fa47337b) 	2024-02-19 03:52:46 	unknown
sd-webui-extended-style-saver 	https://github.com/harukei-tech/sd-webui-extended-style-saver.git 	master 	[7750cc6b](https://github.com/harukei-tech/sd-webui-extended-style-saver/commit/7750cc6b2dcba91951402a682819bcb4fcc43bea) 	2024-01-07 06:45:31 	unknown
sd-webui-openpose-editor 	https://github.com/huchenlei/sd-webui-openpose-editor.git 	main 	[cebe13e0](https://github.com/huchenlei/sd-webui-openpose-editor/commit/cebe13e092fa3c5d810f4afbd7a45987ba8275d0) 	2023-12-19 04:58:26 	unknown
sd-webui-reactor 	https://github.com/Gourieff/sd-webui-reactor.git 	main 	[778ddec9](https://github.com/Gourieff/sd-webui-reactor/commit/778ddec96d92c46e2d9cd6a8721930edd13fc894) 	2024-02-24 13:57:46 	unknown
sd-webui-regional-prompter 	https://github.com/hako-mikan/sd-webui-regional-prompter.git 	main 	[59d68e6e](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/59d68e6e1c49fe2df1e1b483dc0fe6621467435a) 	2024-02-07 17:24:12 	unknown
sd_save_intermediate_images 	https://github.com/AlUlkesh/sd_save_intermediate_images.git 	main 	[24c3ce20](https://github.com/AlUlkesh/sd_save_intermediate_images/commit/24c3ce206a6493c3180fb71a970d5f122cc52fba) 	2023-10-10 15:24:31 	unknown
stable-diffusion-webui-images-browser 	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git 	main 	[3d2d0f4c](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/3d2d0f4c7b0599f88df99a9ea66c21bcbec49bda) 	2024-02-02 15:40:47 	unknown

**Comment by Tesserakt-company** [comment]
Latent produced a good image, then I wanted to generate another one. Latent not implemented. On both latent and active.

**Comment by hako-mikan** [comment]
It's an issue that occurs when using LoHa.
It works fine with Web-UI 1.8.
