### ISSUE TITLE
Can't use more than two masks in Latent mode

### ISSUE THREAD

**Issue by LizardKing777** [hako-mikan/sd-webui-regional-prompter#312]
If I use more than two masks in latent mode, I get this error at every iteration:

```
*** Error executing callback cfg_denoised_callback for /home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
    Traceback (most recent call last):
      File "/home/lizard/Downloads/stable-diffusion-webui/modules/script_callbacks.py", line 224, in cfg_denoised_callback
        c.callback(params)
      File "/home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 591, in denoised_callback
        denoised_callback_s(self, params)
      File "/home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 194, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range
```

OS: Ubuntu 22.04
Web-UI version: Just updated to latest version
SD Version: 1.5 & XL
LoRA/LoCon/LoHa: All not working

**Other Enabled Extensions**
Dynamic Prompts (doesn't work whether active or not)
Dynamic Thresholding (doesn't work whether active or not)
Lora Masks (doesn't work whether active or not)
NegPip (doesn't work whether active or not)
Composible Lora( same)
CD Tuner (same)

**Comment by hako-mikan** [comment]
That happens when the number of masks and the number of specified regions don't match.

**Comment by LizardKing777** [comment]
If I switch to Attention mode and use the exact same prompt and mask it works just fine.

**Comment by hako-mikan** [comment]
Fixed in ae56666.
