### ISSUE TITLE
IndexError when specify batch size

### ISSUE THREAD

**Issue by chthub** [hako-mikan/sd-webui-regional-prompter#324]
**Describe the bug**
when batch size is 1, it works well, but if I set the batch size to 4, it report:

```python
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range
```
I try to debug:
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/45276259/f4e7055f-b3a1-490f-8710-73d415610315)

it seems that the index out of the range of the list:
```python
---
RP Options [False] 1
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range

---
RP Options [False] 2
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range

---
RP Options [False] 2
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range

---
RP Options [False] 3
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range

---
RP Options [False] 3
*** Error creating infotext for key "RP Options"
    Traceback (most recent call last):
      File "/AImage/stable-diffusion-webui/modules/processing.py", line 808, in create_infotext
        generation_params[key] = value[index]
                                 ~~~~~^^^^^^^
    IndexError: list index out of range

```

**Environment**
Web-UI version:1.9.3
SD Version:sdxl1.0
no LoRA/LoCon/LoHa

**Other Enabled Extensions**

**Comment by FriedGenera** [comment]
I'm having the same problem on Web-UI 1.9.4, and it also breaks adetailer when you have multiple prompts.

**Comment by woCmodsiW** [comment]
Web-UI v: [v1.10.1]
This problem is still occurring as previously detailed in the issue.

**Comment by wangbo6886** [comment]
I also have the same problem.
Open adetailer and set batch size > 1.

**Comment by hako-mikan** [comment]
Fixed.
