### ISSUE TITLE
This Error and Many other errors  Happen when im using either Common Prompt or Base Prompt but it works if im not using either of them

### ISSUE THREAD

**Issue by LadyFlames** [hako-mikan/sd-webui-regional-prompter#334]
**Describe the bug**
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\txt2img.py", line 108, in txt2img_function
    processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 785, in run
    processed = script.run(p, *script_args)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\scripts\AutoChar.py", line 829, in run
    last_image_batch = text2img_hr(upscaler, scale_factor0)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\scripts\AutoChar.py", line 578, in text2img_hr
    hr_output = process_images(p)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 922, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules_forge\forge_sampler.py", line 88, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\modules\samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\modules\samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\modules\model_base.py", line 90, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 867, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 55, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\attention.py", line 620, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\attention.py", line 447, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\diffusionmodules\util.py", line 194, in checkpoint
    return func(*inputs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\ldm_patched\ldm\modules\attention.py", line 547, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2, transformer_options=extra_options)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 417, in forward
    ox = matsepcalc(x, contexts, mask, self.pn, 1)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 185, in matsepcalc
    context = contexts[:,tll[i][0] * TOKENSCON:tll[i][1] * TOKENSCON,:]
IndexError: list index out of range
list index out of range
*** Error completing request
*** Arguments: ('task(00s2aexaipvcikx)', <gradio.routes.Request object at 0x000002B80AFB7550>, 'score_9_up, score_8_up, score_7_up, score_6_up, (4K, UHD, Super quality, Super Detail, Super Resolution, Super Definition, Masterfully Crafted, Masterfully Detailed, Masterfully Drawn, Pixel Perfect, Raw Photo, masterpiece, AutoSR, AutoHQ, AutoDef, AutoDetail, DLSR, DLSS3.5, HDR, AMD FSR3, VSR, VFX, Nvidia RTX, Path Tracing, Ray Tracing, Automatic Resolution, Automatic Rendering, Automatic Masterpiece, Automatic prompt Accuracy, Automatic prompt Adherence, Automatic prompt Coherence, Automatic Facial Expressions, Automatic Facial Features, Automatic Dynamic Pose, Automatic Definition, Automatic Composition, Automatic Quality, Automatic Details, Automatic Perfection, Automatic Pixel Perfect, Automatic Textures, Overall Detail, Gorgeous Faces, Beautiful Faces, Beautiful Bodies, Gorgeous Bodies, Professional Detail, Professional Quality, Professional Definition, Professional Resolution, Professional Composition, Professional Rendering, Detailed Hands and Fingers, Perfectly Drawn Hands and Fingers, Perfectly Drawn Legs and Feet, Detailed Legs and Feet, Detailed Female Anatomy, Perfectly Drawn Tongue, Detailed Tongue, Detailed Female Body, Face Enhance, Enhanced Details, Enhance Detail, Enhance Quality, Enhanced Quality, Enhance Resolution, Enhanced Resolution, Enhance Definition, Enhanced Definition, Enhanced Features, Enhance Features, Automatic Features, Perfectly Drawn Features, Detailed Features, Enhanced Facial Features, Highly Detailed, Detailed Faces&Tongues, 5Fingers, FixHand, Perfectly Drawn, Masterfully Crafted, Dynamic Pose, Smooth, Accurate, Flawless, seamless, sharp focus, Tack Sharp, full, detailed, very intricate, illuminated delicate background, cinematic, in action, Textured, Dramatic cinematic lighting, Automatic Visuals:1.2) Best Quality image of (2girls, 2girl, multiple girls, Engaged, Getting Married to each other, Engagement Rings on their Ring Fingers, intimate, Passionate, Erotic, kissing, french kissing, aphrodisiac, saliva, Tongue Play, After Kiss Saliva, saliva trail, Saliva Exchange, saliva swap, Lips locked to each other, Mouths touching each other, Lovers, Family, Cousins&Sisters, yuri:1.2), outdoor, Sandy Beach, Near Crystal Clear Water, Secluded, Private, Furnished Majestic Large Mansion, OutDoor Furnitures, Modern Electronics, OutdoorKitchen, Modern Furnitures, sun rays ADDCOM\n(1girl, Girl, Cat_girl, cat ears), Busty, Voluptuous, Seductive, Beautiful, Beautiful Face, (Pink hair, long hair, Styled Hair, forehead, Empty Eyes Devoid of Free Will:1.2), Cleavage, (((Excessive Breast Growth, Expanding Breasts, Growing Breasts, perfect Full-Round Breasts, K-Cup size Breasts, Swollen Breasts, Bursting Breasts, Oversized Breasts, Colossal Breasts, gigantic breasts, Enormous Breasts, Humongous Breasts, Full-Round Huge Ass:1.3))), (smiling, happy, joyous:1.1), (Fitted, Tailored, Customized, Adjusted, Designed, Custom Made, Partially unbuttoned Shirt, Animal Collar, Thigh Highs, Mini skirt, sleeveless:1.3), (Swallowing Saliva, Under High Arousal, Under Extremely Potent High Dose Aphrodisiac, Entranced, Experiencing Mind Break, mind control, entrancement, Loss of Free Will, Being Trained&Tamed&Subjugated&Owned, In Daze:1.2) ADDCOL\n(1girl, Girl, Vampire, Vampiric, Sharp Pointed Fangs), Beautiful, Beautiful Face, Alluring, dominatrix, owner, Mistress, Subjugator, Trainer&Tamer of Cat Girl, (black hair, short hair, Extremely Potent High Dose Aphrodisiac Laced Lips, hair between eyes, glowing eyes, green eyes:1.2), (blush, embarrassed, shy, shy smile:1.1), (large breasts, medium Breasts:1.2), (white t-shirt, puffy sleeves, shorts:1.3), is actively (Breast Groping, Breast Squeezing, Breast Fondling, Ass Grabbing, grabbing from behind, Taming&Training, Subjugating, Entrancing, Hypnotizing, Enslaving, Dominating, neck biting, Biting, Mind Breaking, Seducing, Administering Extremely Potent High Dose Aphrodisiac using French Kissing, Kissing, Saliva, saliva trail, saliva swap, Saliva Exchange, Owning, Branding, Marking, Mind Controlling, Shaping&Grooming, fingering through panties of 1girl, fingering through clothes, Mind Breaking 1Girl:1.3), (Styling&Coloring 1Girl´s Hair, Applying Lipstick, Tailoring, Customizing, Designing, Fitting, Adjusting, Making 1girl´s Clothing&Outfits:1.3), (Making 1Girl´s Breasts Grow&Expand on a Daily Basis While Making 1Girl Stay in a Constant State of Arousal on Daily Basis:1.2)', 'Score_5, Score_4, Score_3, Score_2, Score_1, mature content, double body, double faces, double features, Extra Features, Double Legs, Double Hands, Double Fingers, Distorted Faces, Distorted Legs, Distorted Hands, Distorted Fingers, Distorted Feet, Distorted Bodies, Ugly Faces, Ugly Legs, Ugly Hands, Ugly Fingers, Hideous Faces, incorrect posture, long legs, close up, (((two heads))), two faces, plastic, pregnant, deformed belly, deformed, blurry, bad anatomy, bad eyes, crossed eyes, disfigured, poorly drawn face, mutation, mutated, {(((extra limb)))}, ugly, (((poorly drawn hands))), missing limb, floating limbs, disconnected limbs, malformed hands, blur, out of focus, long neck, long body, (((mutated hands and fingers))), (((out of frame))), long fingers, blender, doll, cropped, low-res, close-up, poorly-drawn face, out of frame double, two heads, blurred, too many fingers, repetitive, black and white, grainy, extra limbs, bad anatomy, high pass filter, airbrush, portrait, zoomed, soft light, smooth skin, (((extra limbs))), (((extra fingers))), (((mutated hands))), bad anatomy, bad proportions, blind, bad eyes, ugly eyes, dead eyes, vignette, out of shot, out of focus, gaussian\nbad-image-v2-39000-neg bad pictures BadDream BadNegAnatomyV1-neg badquality-neg Beyondv4-neg bhands-neg By bad artist -neg difConsistency negative v2 easynegative EasyNegativeV2 FastNegativeV2 fcNeg-neg HandNeg-neg negative hand-neg NegfeetV2 NegFixBadPhoto-neg ng deepnegative v1 75t Unspeakable-Horrors-Composition-4v UnrealisticDream SimpleNegativeV3 verybadimagenegative v1.3, Male Focus, No Men, No Malformations, No Deformations, No Errors, JPEG Artifacts, No Body Horrors, twisted, Hideous, Gross, Grotesque, PoorlyDrawn Hands and Fingers, LowDetail, LowRes, LowQuality, NormalQuality, No men, No Males, More than 2Girls, Less than 2Girls, Double Features, Extra Body Parts, Double body Parts, Extra Features, inaccurate, inconsistent, No Fused Body Parts, No Malformed Body Parts, No Twisted Body Parts, No Edge Artifacts, PoorlyDrawn Face and Tongue, PoorlyDetailed Hands and Fingers, PoorlyDetailed Legs and Feet, Resolution mismatch, Quality Mismatch, Definition MisMatch, inconsistent Details, Artifacts, No JPEG Artifacts, No Artifacts, No Extra Objects, No unnecessary object, incomplete, Disgusting, More than 5 Fingers, Less than 5 Fingers, Blemishes, No Blemishes, blurry foreground, blurry background, blurry, low resolution, deformed bodies, incorrect lighting, floating objects, empty background, poor perspective, extra limbs, out of frame, mutated, bad proportions, grainy, overexposed, underexposed, black and white, zoomed in, vignette, childish, cartoonish, unrealistic, pixelated, overly exaggerated features, unnatural poses, excessive gore, disturbing, offensive, violent, poor anatomy, low quality, generic, plain, boring, empty environment, lack of details, poorly drawn faces, overly simplistic, flat, bad composition, uninspired, male focus, No Male Presence, Extra Nipples, Double Nipples, Ugly Lips, PoorlyDrawn Lips, Ugly Tongue, PoorlyDrawn Tongue, Saturated, oversaturated, mosaic censoring, out of frame, out of focus', [], 80, 'DPM++ 2M Karras', 30, 1, 30, 768, 768, False, 0.5, 1.2, 'Latent (bicubic antialiased)', 40, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 1, False, 'SD3\\stableDiffusion3SD3_sd3MediumInclClips.safetensors [3bb7f21bc5]', 0.5, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, 'keyword prompt', 'keyword1, keyword2', 'None', 'model keyword first', 'None', '0.7', 'None', False, 30, 0, 'full', 0, 'middle', 0, '', False, 7, 3, 0, 'full', 0, 0.0, 1.0, True, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.3,0.6', True, False, False, 'Attention', ['[', 'F', 'a', 'l', 's', 'e', ']'], '0', '0', '0.4', None, '0', '0', False, False, 0.0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, multi_inputs_gallery=None, generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, multi_inputs_gallery=None, generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, True, 0.3, 'Latent (bicubic antialiased)', 0.5, 0.5, 0.5, 0.5, ['Automatic face inpaint', 'Automatic eyes inpaint'], 'Txt2Img', True, 2, 1.2, True, True, False, 5, 64, False, 0.3, 0.6, True, True, True, False, '', '', '', '', '', '', 40, 'DPM++ 2M Karras', 40, 'DPM++ 2M Karras', 40, 'DDIM', 'Use same checkpoint', 'Use same checkpoint', 'Use same checkpoint', 2.5, 1.5, 2, 2, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, [], 30, '', 4, [], 1, '', '', '', '') {}
    Traceback (most recent call last):
      File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 616, in create_unit
    return ControlNetUnit.from_dict({
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\lib_controlnet\external_code.py", line 297, in from_dict
    unit.hr_option = HiResFixOption(unit.hr_option)
  File "enum.py", line 385, in __call__
  File "enum.py", line 710, in __new__
ValueError: 'HiResFixOption.BOTH' is not a valid HiResFixOption
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 616, in create_unit
    return ControlNetUnit.from_dict({
  File "D:\Stability Matrix\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\lib_controlnet\external_code.py", line 297, in from_dict
    unit.hr_option = HiResFixOption(unit.hr_option)
  File "enum.py", line 385, in __call__
  File "enum.py", line 710, in __new__
ValueError: 'HiResFixOption.BOTH' is not a valid HiResFixOption

**Environment**
Web-UI version:Forge Dev2
SD Version:1.5 Personal Merge
LoRA/LoCon/LoHa:None

**Other Enabled Extensions**
AutoChar
AutoTag Complete
Adetailer
ModelKeyWord
webui-fooocus-prompt-expansion
sd-webui-prompt-format
sd-perturbed-attention

**Comment by hako-mikan** [comment]
Dose this error occur in latest version?

**Comment by hako-mikan** [comment]
This is an issue with an older version of Forge, so please let me know if you encounter the same error with the latest version.
