### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by Natans8** [hako-mikan/sd-webui-regional-prompter#342]
In the recent [WebUI Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) updates, Regional Prompted is unable to even load. since there were many fundamental changes to both backend and frontend, including the switch to Gradio 4. Currently, Regional Prompter is the last plugin that holds me back from switching completely to Forge, since Forge seems to be overall better optimized, and supports features like Flux that A1111 does not.

It would be great to adapt, if not to Flux, than at least to keep the existing SD1.5/SDXL capabilities in Forge. Thank you in advance!

Below in the log of WebUI Forge when trying to start with Regional Prompter.

```
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "C:\Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "C:\Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Forge\extensions\sd-webui-regional-prompter\scripts\latent.py", line 11, in <module>
        import scripts.attention as att
      File "C:\Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "C:\Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Forge\extensions\sd-webui-regional-prompter\scripts\rp.py", line 15, in <module>
        import scripts.attention
      File "C:\Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'
```

**Comment by metapea** [comment]
Regional Prompter (Attention mode) works in reforge still.

**Comment by jkw117** [comment]
On my new install of the regional prompter the ui fails to load the module ldm.modules at all.  And never gets added to the gui..

**Comment by Kuzhnya** [comment]
[Natans8](https://github.com/Natans8), just open file with notepad `webui\extensions\sd-webui-regional-prompter\scripts\attention.py`
Then change line 3 from `import ldm.modules.attention as atm` to `import modules as atm` 
it's works for me

**Comment by steamrick** [comment]
Can confirm, I get the same error

File "E:\AI Art Stuff\forge\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

**Comment by githabtane** [comment]
数日前のアップデートで他の拡張機能も
同じ種類のエラーが出ています
gradio 4　forgeに対応予定でしょうか？
マスクモードは特に気に入っていました

**Comment by ToolB0xx** [comment]
yeah also broken for me after updating forge, hope it works soon

**Comment by LuoICharlin** [comment]
try to copy the 'ldm' folder in "..\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai" to the root "..\stable-diffusion-webui-forge" could solve this problem.
I use this method to run regional prompt on the latest Stable Diffusion Forge successfully.

**Comment by chen079** [comment]
try to copy the 'ldm' folder in "..\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai" to the root "..\stable-diffusion-webui-forge" could solve this problem.
I use this method to run regional prompt on the latest Stable Diffusion Forge successfully.

**Comment by chen079** [comment]
> try to copy the 'ldm' folder in "..\stable-diffusion-webui-forge\repositories\stable-diffusion-stability-ai" to the root "..\stable-diffusion-webui-forge" could solve this problem. I use this method to run regional prompt on the latest Stable Diffusion Forge successfully.

but when using XL model, this error has happened:
*** Error running postprocess: F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "F:\AIDraw\stable-diffusion-webui-forge\modules\scripts.py", line 900, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\rp.py", line 600, in postprocess
        unloader(self, p)
      File "F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\rp.py", line 621, in unloader
        unloadlorafowards(p)
      File "F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\latent.py", line 573, in unloadlorafowards
        emb_db = sd_hijack.model_hijack.embedding_db
    AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'

---
1,1 0.2 Horizontal
*** Error running process: F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "F:\AIDraw\stable-diffusion-webui-forge\modules\scripts.py", line 844, in process
        script.process(p, *script_args)
      File "F:\AIDraw\stable-diffusion-webui-forge\extensions\sd-webui-regional-prompter\scripts\rp.py", line 502, in process
        self.handle = hook_forwards(self, p.sd_model.model.diffusion_model)
    AttributeError: 'StableDiffusionXL' object has no attribute 'model'

---

**Comment by fishonainternet** [comment]
Just use the older version of ForgeUI, it works

**Comment by vitrvvivs** [comment]
This is not the correct way to fix it, as it will propably break non-forge setups (I didn't test that), but it is the way I found to get it working again.

```diff
diff --git a/scripts/latent.py b/scripts/latent.py
index 7d0dcc3..de60abb 100644
--- a/scripts/latent.py
+++ b/scripts/latent.py
@@ -570,7 +570,8 @@ def unloadlorafowards(p):
     except:
         pass

-    emb_db = sd_hijack.model_hijack.embedding_db
+    from modules import ui_extra_networks_textual_inversion
+    emb_db = ui_extra_networks_textual_inversion.embedding_db
     import lora
     for net in lora.loaded_loras:
         if hasattr(net,"bundle_embeddings"):
diff --git a/scripts/rp.py b/scripts/rp.py
index 93b4466..34272f2 100644
--- a/scripts/rp.py
+++ b/scripts/rp.py
@@ -499,14 +499,14 @@ class Script(modules.scripts.Script):

             ##### calcmode
             if "Att" in calcmode:
-                self.handle = hook_forwards(self, p.sd_model.model.diffusion_model)
+                self.handle = hook_forwards(self, p.sd_model.forge_objects.unet.model.diffusion_model)
                 if hasattr(shared.opts,"batch_cond_uncond"):
                     shared.opts.batch_cond_uncond = orig_batch_cond_uncond
                 else:
                     shared.batch_cond_uncond = orig_batch_cond_uncond
                 unloadlorafowards(p)
             else:
-                self.handle = hook_forwards(self, p.sd_model.model.diffusion_model,remove = True)
+                self.handle = hook_forwards(self, p.sd_model.forge_objects.unet.model.diffusion_model,remove = True)
                 setuploras(self)
                 # SBM It is vital to use local activation because callback registration is permanent,
                 # and there are multiple script instances (txt2img / img2img).
@@ -514,7 +514,7 @@ class Script(modules.scripts.Script):
         elif "Pro" in self.mode: #Prompt mode use both calcmode
             self.ex = "Ex" in self.mode
             if not usebase : bratios = "0"
-            self.handle = hook_forwards(self, p.sd_model.model.diffusion_model)
+            self.handle = hook_forwards(self, p.sd_model.forge_objects.unet.model.diffusion_model)
             denoiserdealer(self)

         neighbor(self,p)                                                    #detect other extention
@@ -608,7 +608,7 @@ class Script(modules.scripts.Script):
 def unloader(self,p):
     if hasattr(self,"handle"):
         #print("unloaded")
-        hook_forwards(self, p.sd_model.model.diffusion_model, remove=True)
+        hook_forwards(self, p.sd_model.forge_objects.unet.model.diffusion_model, remove=True)
         del self.handle

     self.__init__()
@@ -711,7 +711,7 @@ def tokendealer(self, p):

     padd = 0

-    tokenizer = shared.sd_model.conditioner.embedders[0].tokenize_line if self.isxl else shared.sd_model.cond_stage_model.tokenize_line
+    tokenizer = shared.sd_model.conditioner.embedders[0].tokenize_line if self.isxl else shared.sd_model.text_processing_engine_l.tokenize_line

     for pp in ppl:
         tokens, tokensnum = tokenizer(pp)
```

**Comment by queenofinvidia** [comment]
> This is not the correct way to fix it, as it will propably break non-forge setups (I didn't test that), but it is the way I found to get it working again.

This is awesome! can you please explain what I do with this? as a non code savvy person?

Thank you <3

**Comment by vitrvvivs** [comment]
@queenofinvidia https://stackoverflow.com/questions/12320863/how-do-you-take-a-git-diff-file-and-apply-it-to-a-local-branch-that-is-a-copy-o

**Comment by BrianAllred** [comment]
@vitrvvivs neither `git apply fix.diff` nor `patch -i fix.diff` work for me. Both say the patch does not apply.

**Comment by vitrvvivs** [comment]
@BrianAllred shoot, I think that's whitespace errors. The repo uses CRLF and has trailing spaces all over the place. While github strips trailing spaces in comments.
```
git config core.whitespace cr-at-eol
git apply --whitespace=fix fix.diff
```

I should mention I also used @chen079 's suggestion
```
stable-diffusion-webui$  cp -r repositories/stable-diffusion-stability-ai/ldm ./
```

**Comment by Tarkian10** [comment]
I'm absolutely disgusted with the Forge update, which has tons of issues, including breaking Regional Prompter. Is there a temporary alternative or a similar extension?

Going back to A1111 and its slowness unfortunately seems like the only solution...

**Comment by Natans8** [comment]
> I'm absolutely disgusted with the Forge update, which has tons of issues, including breaking Regional Prompter. Is there a temporary alternative or a similar extension?
> 
> Going back to A1111 and its slowness unfortunately seems like the only solution...

You could just use an older version of Forge, iirc it's explained in the README.

**Comment by MoeMonsuta** [comment]
> > I'm absolutely disgusted with the Forge update, which has tons of issues, including breaking Regional Prompter. Is there a temporary alternative or a similar extension?
> > Going back to A1111 and its slowness unfortunately seems like the only solution...
> 
> You could just use an older version of Forge, iirc it's explained in the README.



> I'm absolutely disgusted with the Forge update, which has tons of issues, including breaking Regional Prompter. Is there a temporary alternative or a similar extension?
> 
> Going back to A1111 and its slowness unfortunately seems like the only solution...

I heard https://github.com/Panchovix/stable-diffusion-webui-reForge is a good solution for quickly swapping versions.

**Comment by Tarkian10** [comment]
Thank you for your answers! I don't know why I didn't think of it, but it now seems obvious to use the previous July version. I'm relieved, I’ll be able to resume my work.

**Comment by derfasthirnlosenick** [comment]
> @BrianAllred shoot, I think that's whitespace errors. The repo uses CRLF and has trailing spaces all over the place. While your editor probably uses LF, and github stripped all the trailing spaces from the comments. Both of which cause the patch to fail to match.
> 
> ```
> git config core.whitespace cr-at-eol
> git apply --whitespace=fix fix.diff
> ```
> 
> I should mention I also used @chen079 's suggestion
> 
> ```
> stable-diffusion-webui$  cp -r repositories/stable-diffusion-stability-ai/ldm ./
> ```

funny thing. works as long as I don't use common prompt, then it just doesn't do the regional prompts but blends them somehow (or forgets one).
`green hair twintail BREAK
red blouse BREAK
blue skirt`
works, 

`best quality, 20yo lady in garden BREAK
green hair twintail BREAK
red blouse BREAK
blue skirt`
misses the red blouse and gives me a dress.
Weird. Any suggestions on how to debug?

**Comment by mperez96** [comment]
Got the same error, just commenting to promote the solution of this, will be awesome to have the possibility to use it with flux but we'll see.

Couldn't make any of the solutions mentioned before to work (didn't try to go back the version, but I honestly prefer having flux than regional prompter for now as I can use it in A1111 I guess)

`*** Error loading script: attention.py
    Traceback (most recent call last):
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 11, in <module>
        import scripts.attention as att
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 15, in <module>
        import scripts.attention
      File "D:\Users\USER\Documents\AI\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'`

**Comment by rsigim** [comment]
[this fork is working with recent forge](https://github.com/jessearodriguez/sd-forge-regional-prompter)

**Comment by steamrick** [comment]
> [this fork is working with recent forge](https://github.com/jessearodriguez/sd-forge-regional-prompter)

I can confirm it works (and installing it lets the main regional prompter show up though not work), but only with SDXL (and presumably SD1.5). I couldn't get it to do any regional functionality with a Flux model, unfortunately.

**Comment by DrJimmyBrungus** [comment]
> [this fork is working with recent forge](https://github.com/jessearodriguez/sd-forge-regional-prompter)

Can also confirm this is working on Forrge with PonyXL models / LORAs. Nice work,

**Comment by queenofinvidia** [comment]
Does the masking feature work too? I'm still getting an error

**Comment by titlestad** [comment]
> [this fork is working with recent forge](https://github.com/jessearodriguez/sd-forge-regional-prompter)

No it doesn't work. It has an error (pt) as written elsewhere. The fork is useless with the latest forge - which is a shame.

**Comment by derfasthirnlosenick** [comment]
> > [this fork is working with recent forge](https://github.com/jessearodriguez/sd-forge-regional-prompter)
> 
> No it doesn't work. It has an error (pt) as written elsewhere. The fork is useless with the latest forge - which is a shame.

Is this recent? BC I got it working a while back, but haven't tried it since a few days.

**Comment by hako-mikan** [comment]
The issue with ldm has been resolved. 
It now supports Latent mode as well as region-specific adaptation for LoRA. 
However, there are likely still multiple bugs remaining, so I believe there’s still much work to be done before it can be considered fully functional.

**Comment by hako-mikan** [comment]
The Forge/reForge support is mostly complete. 
If any new errors occur, please create a new issue.
