### ISSUE TITLE
ldm problem with webui forge

### ISSUE THREAD

**Issue by tezukaaaa** [hako-mikan/sd-webui-regional-prompter#349]
**
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\latent.py", line 11, in <module>
        import scripts.attention as att
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\rp.py", line 15, in <module>
        import scripts.attention
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---**
i use stability matrix launcher and work with webui forge. when i tried to run this extension, i see this 

**Stability matrix, windows 11,Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17)**
Web-UI version: stable diffusion webui forge
SD Version: -
LoRA/LoCon/LoHa -

**
![image](https://github.com/user-attachments/assets/60862d39-a1c2-4d6b-938f-c72c825af967)
**

**Comment by snintendog** [comment]
same been trying to get it working.

**Comment by hako-mikan** [comment]
Fixed and same to #342.
