### ISSUE TITLE
No module named 'ldm'

### ISSUE THREAD

**Issue by GUnd4m1** [hako-mikan/sd-webui-regional-prompter#353]
**Describe the bug**
failed to run the extension

Error loading script: rp.py
    Traceback (most recent call last):
      File "C:\Users\PC\AI Stuff\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\PC\AI Stuff\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\PC\AI Stuff\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 15, in <module>
        import scripts.attention
      File "C:\Users\PC\AI Stuff\webui_forge_cu121_torch231\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

(idk anything about coding so please help)

**Environment**
Web-UI version:
SD Version: SDXL
LoRA/LoCon/LoHa

**Other Enabled Extensions**

**Comment by K1LL3RPUNCH** [comment]
+1

**Comment by MoeMonsuta** [comment]
Even after fixing ldm the extension is still broken on Forge. Project seems archived and abandoned. Look into Forge Couple instead. https://github.com/Haoming02/sd-forge-couple

**Comment by hako-mikan** [comment]
Fixed and same to #342.
