### ISSUE TITLE
Sometime Runtime Error when using Base Prompt

### ISSUE THREAD

**Issue by Ptibouc77** [hako-mikan/sd-webui-regional-prompter#49]
Hi, im using the amd directml automatic1111 version,

When i toggle the `Use base prompt` option i almost get everytime this RuntimeErrorr:
(Maybe 1 of 5 of chance to actually works)

`Traceback (most recent call last):
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\processing.py", line 635, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\processing.py", line 835, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 599, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 138, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\amd_sd\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 778, in forward
    h = module(h, emb, context)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\amd_sd\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 1064, in forward
    ox = regsepcalc(x, contexts, mask, self.pn, 1)
  File "C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 994, in regsepcalc
    out = main_forward(module, x, context, mask, divide, self.isvanilla)
  File "C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 283, in main_forward
    k = module.to_k(context)
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\amd_sd\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "C:\amd_sd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError`

Any idea why do this happen?

This is example of the prompt i use:

```
wide angle, {__mywildcards/camera_angle_etc__}, photographed by a {__mywildcards/camera__}, {__mywildcards/camera_lens__}, shallow depth of field, (sharp focus:0.4), simple background, (blurry background:0.3), 8k, best quality, masterpiece, intricate details, (soft lighting:0.8), photoreal, photorealistic, photography, atmospheric perspective, textured skin, (highly detailed photo:0.7), (detailed realistic skin:1.3), (skin pores:1.3), {0-4$$__mywildcards/details__}, {0-2$$ and $$__mywildcards/jewelry_etc__}BREAK
a woman with blonde hair, {__mywildcards/outside_inside_places__} {at|during} {daytime|nighttime}, {__mywildcards/woman_pose__}, BREAK
wearing a ({__mywildcards/color__} {1-2$$ and $$__mywildcards/clothes_top__} {__mywildcards/pattern__}, { __mywildcards/texture__}), BREAK
wearing a ( {__mywildcards/color__} {1-2$$ and $$__mywildcards/clothes_bottom__} {__mywildcards/pattern__}, { __mywildcards/texture__}), 
```
My Regional Prompter settings;
Divide mode -Vertical
Divide Ratio -1,1,1
Generation mode -Attention
Base Ratio -0.2
Use Base Prompt Checked (others unchecked)

**Comment by Symbiomatrix** [comment]
Hello. When does this error occur - after an unpredictable number of iterations have passed, or at a particular stage?
Have you tried a simpler prompt (no wildcards)?

**Comment by Ptibouc77** [comment]
This mostly occur when i hit Generate, i see the 0/20 steps in command line but it instantly stop, and give me the Runtime Error.
I will try to use some batches without wildcards to see if something change (i will update this message when is done)
I run it on a Rx 6600 and i can do 512x768 without any problem (everything higher than that is unstable "No enought GPU Memory" message)
I also run it with `COMMANDLINE_ARGS=--autolaunch --medvram --api --precision full --no-half --no-half-vae --opt-split-attention-invokeai --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --upcast-sampling --use-cpu interrogate gfpgan bsrgan esrgan scunet codeformer`

**Comment by Symbiomatrix** [comment]
I see it's relatively recent, ranked a bit lower than 3060 though far less vram. Wonder if that might be an issue. Have you monitored memory usage to see if it's capped out in those gens?

**Comment by Sakura-Luna** [comment]
Might not be relevant, but the parameters you're using are messy, try using `COMMANDLINE_ARGS=--autolaunch --medvram --api --no-half-vae --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --use-cpu interrogate gfpgan bsrgan esrgan scunet codeformer,` this will allow you to generate slightly larger images.

**Comment by Ptibouc77** [comment]
I did a batch of 65 images with these settings:
512x768 / Restore Faces / Steps: 20
Regional Prompter: Use Base Prompt /  Vertical / 1,1,1 / Attention / 0.2

Prompt:
`wide angle,looking at viewer, photographed by a Nikon D850 DSLR Camera, 85mm Lens, shallow depth of field, (sharp focus:0.4), simple background, (blurry background:0.3), 8k, best quality, masterpiece, intricate details, (soft lighting:0.8), photoreal, photorealistic, photography, atmospheric perspective, textured skin, (highly detailed photo:0.7), (detailed realistic skin:1.3), (skin pores:1.3), lipstick, bracelet, BREAK
a woman with blonde hair, in a train station at daytime, in a walking pose, BREAK
wearing a (white tank_top with polka dot pattern, frayed) BREAK
wearing a (red skirt with vertical stripes pattern, jeans) `

It seems to be working fine without wildcards, no Ryntime Error i also tried to run multiple anothers instance after the first one to trigger the Runtime Error but i only had a random "GPU Not enough Memory error" but this is one must be related to AMD DirectML vram mangement cause it can happen sometime without any reason...
But anyway without Wildcards the Runtime Error doesn't occur.

> Might not be relevant, but the parameters you're using are messy, try using `COMMANDLINE_ARGS=--autolaunch --medvram --api --no-half-vae --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --use-cpu interrogate gfpgan bsrgan esrgan scunet codeformer` this will allow you to generate slightly larger images.

I also tried your COMMANDLINE_ARGS= but without succes, it seems to only generate black images...
So i put back `--precision full --no-half --opt-split-attention-v1` and it seems to be a little bit faster

This is what i use now : `COMMANDLINE_ARGS=--autolaunch --medvram --api --precision full --no-half --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --use-cpu interrogate gfpgan bsrgan esrgan scunet codeformer`

**Comment by Symbiomatrix** [comment]
Awesome, so it sounds like compatibility with wildcards is the issue at hand (though the gpu / environment might still have something to do with it). I'd guess either the quantity (eg exceeding the preset number of tokens after replace, since hako's tokenizer counts these), or specific bad files.
If you'd care to do some testing, you could go about it like this:
- You've said that the crash was very frequent with your original prompt, so running ~3-5 batches should suffice for each step. The strategy is replacing some of the wildcards with a fixed value from their list per step.
- Run the prompt with one wildcard and see if it crashes, if it does it might be severe incompatibility (somewhat unlikely).
- Run the prompt with only the first half of the wildcards.
- Same with the second half.
- If neither crashed, increase the number of wildcards by 50%; at some point it must crash (and it's likely due to quantity, in some way).
- If only one or both crashed, decrease quantity by 50%; this could either converge to several bad files or a low tolerance for wildcards.
It would also be useful if the replaced prompts were printed (try to run a wildcard prompt that crashed with fixed values).

I'm definitely seeing some issues: regional for me runs before wildcards, and so the tokendealer is completely unaware of how many tokens there actually will be (seems to guess a fixed 4). No runtime errors, however.

**Comment by Symbiomatrix** [comment]
Uh, question - what are these $$?

**Comment by Ptibouc77** [comment]
Will try to do theses tests, and i will update later.


> Uh, question - what are these $$?

Thay are for randomzie number `{1-2$$ and $$__mywildcards/colors__}` this means he will choose 1 or 2 colors 
Can also just be written like this `{1-2$$__mywildcards/colors__}`
The first one  `1-2$$ and $$` replace default `,` by the word `and`

**Comment by Sakura-Luna** [comment]
> I also tried your COMMANDLINE_ARGS= but without succes, it seems to only generate black images...
So i put back `--precision full --no-half --opt-split-attention-v1` and it seems to be a little bit faster

This is not normal, you can post an issue in the project repository to resolve the issue. And `--opt-split-attention-v1` and `--opt-sub-quad-attention` will not take effect at the same time.

**Comment by hako-mikan** [comment]
The strange thing is that LoRA error is occurring.
Is there a LoRA-related word in the wildcard?

**Comment by Symbiomatrix** [comment]
@hako-mikan Pretty sure it's a red herring. Apparently someone thought it clever to override a whole buncha torch methods with custom lora functions in lora_script. Just... wow. Anyway, to_k seems to be an instance of nn.Linear, and that class I reckon is designed to run .forward on call, so there you have it.

```
torch.nn.Linear.forward = lora.lora_Linear_forward
torch.nn.Linear._load_from_state_dict = lora.lora_Linear_load_state_dict
torch.nn.Conv2d.forward = lora.lora_Conv2d_forward
torch.nn.Conv2d._load_from_state_dict = lora.lora_Conv2d_load_state_dict
torch.nn.MultiheadAttention.forward = lora.lora_MultiheadAttention_forward
torch.nn.MultiheadAttention._load_from_state_dict = lora.lora_MultiheadAttention_load_state_dict
```

**Comment by Symbiomatrix** [comment]
Have you restarted the webui since then? There's always the possibility of vram leak.
