### ISSUE TITLE
How do you install your extension in the webui?

### ISSUE THREAD

**Issue by BeaverInGreenland** [hako-mikan/sd-webui-regional-prompter#5]
Hello,
Thank you for your extension. Can you tell us how do you add your script as an extension to the sd webui?

**Comment by Symbiomatrix** [comment]
There should be a tab for that, Once installed, pressed "Apply and restart UI". Alternatively, download the repo as a zip and decompress it in the webui's extensions folder.
After that, there should be a "regional prompter" tab above the scripts list, which needs to be enabled, and the rest of the instructions are in the readme, 

![image](https://user-images.githubusercontent.com/41131377/226930306-b5f4e4d1-fab5-468e-99be-51c062747904.png)

**Comment by 2blackbar** [comment]
doesnt work, gives error 

`[[0, 1.0]] [[[0, 0.5], [0.5, 1.0]]]
pos tokens : [9], neg tokens : [1]
  0%|                                                                                           | 0/22 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(876ng98auuev86y)', 'dog and cat , painting by ilya repin ', 'worst ', [], 22, 17, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, '', 0, <scripts.external_code.ControlNetUnit object at 0x0000013311868C10>, <scripts.external_code.ControlNetUnit object at 0x0000013311868C40>, True, False, 'Vertical', '1,1', '0.2', True, False, False, 'Attention', False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "F:\sd\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\sd\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\sd\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "F:\sd\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "F:\sd\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\sd\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\sd\modules\sd_samplers_kdiffusion.py", line 360, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\sd\modules\sd_samplers_kdiffusion.py", line 236, in launch_sampling
    return func()
  File "F:\sd\modules\sd_samplers_kdiffusion.py", line 360, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\sd\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sd\repositories\k-diffusion\k_diffusion\sampling.py", line 682, in sample_dpmpp_2m_test
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\modules\sd_samplers_kdiffusion.py", line 128, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "F:\sd\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "F:\sd\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "F:\sd\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\venv\lib\site-packages\tomesd\patch.py", line 172, in forward
    return super().forward(*args, **kwdargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "F:\sd\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "F:\sd\venv\lib\site-packages\tomesd\patch.py", line 52, in _forward
    x = u_c(self.attn2(m_c(self.norm2(x)), context=context)) + x
  File "F:\sd\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\sd\extensions\sd-webui-regional-prompter\scripts\rp.py", line 953, in forward
    ox = regsepcalc(x, contexts, mask, True, 1)
  File "F:\sd\extensions\sd-webui-regional-prompter\scripts\rp.py", line 945, in regsepcalc
    ox = torch.cat(h_states, dim=1)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

**Comment by Symbiomatrix** [comment]
@2blackbar Please read the instructions on the front page. Your prompt, "dog and cat , painting by ilya repin", contains no region specifiers, so the extension doesn't know what you want to do. It's not a magic parser.
It could possibly be formatted like so:
painting by ilya repin ADDBASE dog ADDCOL cat
1,1 vertical mode
Might need an additional segment to ensure you get two subjects rather than catdog.

(Side note, might want to ignore no regions case, but then it might be better if the user is informed they've done something wrong; perhaps throw a specific valueerror if prompt contains no breaks.)

**Comment by hako-mikan** [comment]
@Symbiomatrix
Fixed. Disable script when there is no BREAKs
