### ISSUE TITLE
When using a number that is not a multiple of 8 as the dimension of the image to be generated, a RuntimeError occurs.

### ISSUE THREAD

**Issue by NalihznehC** [hako-mikan/sd-webui-regional-prompter#53]
When the aspect ratio of the generated image is smaller than 3:4, e.g. 2:3, 540x810,
something like this:
`RuntimeError: shape '[1, 51, 34, 320]' is invalid for input of size 2165440`
will occur.
3:4 images (600x800) worked well for me.

**Comment by Sakura-Luna** [comment]
It's not like the extension will cause the problem, the same parameter you can generate when the extension is turned off?

**Comment by NalihznehC** [comment]
> It's not like the extension will cause the problem, the same parameter you can generate when the extension is turned off?

When I organize the prompt and generate without the extension, I can generate 600x900 images; 
I double-checked and found out that actually, I can generate smaller images (480x720) with the extension; 
However, when the image size increased to 500x750, the error popped out:
```
pos tokens : [53, 36, 17, 56, 45, 23, 56, 47, 53, 37, 35, 58, 41, 33, 30, 33, 30, 33, 30], neg tokens : [412]

Error completing request
Arguments: ('task(69mvmc7ja6maze4)', '(solo:1.5), solo focus, cute, victorian maid, ADDCOMM \n(simple background, white background:1.2), upper body, 1girl, black hair, long hair, straight hair, black puffy sleeves, short sleeves, arm up, white cuffs, hand, white gloves, bare arm, ADDCOL \nupper body, 1girl, maid headdress, black hair, hime cut, blunt bangs, smile, relaxed, eyebrows, ADDCOL \n(simple background, white background:1.2), ADDROW \n(simple background, white background:1.2), upper body, 1girl, black hair, (long hair:1.4), straight hair, white shirt, black puffy sleeves, short sleeves, white cuffs, white gloves, bare arm, hand, arm up, ADDCOL \nupper body, 1girl, black hair, (hime cut, blunt bangs:1.4), (purple eyes, detailed eyes, sharp eyes:1.2), emotionless, relaxed, looking at viewer,  ADDCOL \n(simple background, white background:1.2), arm down, maid apron, ADDROW \n(simple background, white background), upper body, 1girl, standing, black hair, (long hair:1.4), straight hair, white shirt, black puffy sleeves, short sleeves, white cuffs, bare arm, arm up, maid apron, ADDCOL\nupper body, 1girl, standing, large breasts, white shirt, shirt collar, (black bow:1.1), black puffy sleeves, short sleeves, white cuffs, bare arm, maid apron, ADDCOL\n(simple background, white background), upper body, 1girl, standing, black hair, (long hair:1.4), straight hair, white shirt, black puffy sleeves, short sleeves, white cuffs, bare arm, arm down, ADDROW \n(simple background, white background), upper body, 1girl, standing, black hair, (long hair:1.4), straight hair, white shirt, ADDCOL\nupper body, 1girl, standing, large breasts, white shirt, black corset, clothes around waist, maid apron, ADDCOL\n(simple background, white background), upper body, 1girl, standing, black hair, (long hair:1.4), straight hair, white shirt, black puffy sleeves, short sleeves, white cuffs, (white gloves:1.2), bare arm, hand, arm down, ADDROW \n(simple background, white background:1.2), 1girl, standing, black hair, (long hair:1.4), straight hair, black dress, maid apron, dress frills, ADDROW \n(simple background, white background:1.2), black skirt, black hair, (long hair:1.4), straight hair, dress frills, ADDCOL \n(simple background, white background:1.2), standing, bare legs, white garter straps, dress frills, ADDCOL \n(simple background, white background:1.2), black skirt, black hair, (long hair:1.4), straight hair, dress frills, ADDROW \n(simple background, white background:1.2), black hair, (long hair:1.4), straight hair, dress frills, ADDCOL \n(simple background, white background:1.2), standing, white garter straps, white stockings, white lace trim, white lace, ADDCOL \n(simple background, white background:1.2), black hair, (long hair:1.4), straight hair, dress frills, ', '(bad-artist-anime, bad-artist:1.1), (bad-prompt-v2, bad_prompt:0.8), (bad-image-v2-39000, vile_prompt3:0.4), (low quality:1.3), (worst quality:1.3), (monochrome), (obese:1.3), ugly, black background, multiple people, animal, (short hair:1.6), ADDCOMM\n(deformed, bad anatomy:1.3), (extra limbs:1.35), (malformed hands, poorly drawn hands, mutated fingers:1.4), (bad-hands-3, bad-hands-5:0.2), (twintails, ponytail, braid:1.5), wings, ADDCOL\n(deformed, bad anatomy:1.3), (animal ears:1.4), (twintails, ponytail, braid:1.8), earrings, ear piercing, anchor symbol, ADDCOL\ndeformed, bad anatomy, (twintails, ponytail, braid:1.5), arm up, wings, ADDROW\n(deformed, bad anatomy:1.3), (extra limbs:1.35), (malformed hands, poorly drawn hands, mutated fingers:1.4), (bad-hands-3, bad-hands-5:0.2), (twintails, ponytail, braid:1.8), wings, ADDCOL\n(deformed, bad anatomy:1.3), (poorly drawn face:1.4), (animal ears:1.4), pointy ears, different eyes, (twintails, ponytail, braid:1.5), headband, headdress,  ADDCOL\ndeformed, bad anatomy, (twintails, ponytail, braid:1.2), arm up, wings, ADDROW\n(deformed, bad anatomy:1.3), (extra limbs:1.35), (twintails, ponytail, braid:1.1), wings, ADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), small breasts, ADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), (malformed hands, poorly drawn hands, mutated fingers:1.4), (bad-hands-3, bad-hands-5:0.2), arm up, wings, ADDROW\ndeformed, bad anatomy, ADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), small breasts, bow, ADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), (malformed hands, poorly drawn hands, mutated fingers:1.4), (bad-hands-3, bad-hands-5:0.2), ADDROW\n(deformed, bad anatomy:1.3), extra limbs, ADDROW\nADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), ADDCOL\nADDROW\nADDCOL\n(deformed, bad anatomy:1.3), (extra limbs:1.35), black stockings, ADDCOL\n', [], 25, 15, False, False, 1, 1, 7, 448564851.0, -1.0, 0, 0, 0, False, 750, 500, True, 0.7, 2, 'R-ESRGAN 4x+ Anime6B', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 1536, 96, False, '', 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x0000028B83CFBB80>, <scripts.external_code.ControlNetUnit object at 0x0000028B83CFB1C0>, <scripts.external_code.ControlNetUnit object at 0x0000028B83CF8940>, <scripts.external_code.ControlNetUnit object at 0x0000028B83B370A0>, False, '', 0.5, True, False, '', 'Lerp', False, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nflat:1,0,0,0,0,0,0,0,1.2,0,0,0,0,0,1,0,0,1,1,1.5,1,1,1,1.3,1.3,1\nres:1,1,1,1,1,0.5,0.5,0.5,1,1,1,1,1,1,1,0.5,0.5\ncharacter:1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0\nACTION:1,0,0,0,0,0,0.2,1,1,1,0,0,0,0,0,0,0\nBACK:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\nNF:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nface:1,0,0,0,0,0,0,0,0.8,1,1,0.2,0,0,0,0,0\npaint:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\nOUTFIT:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0\nFACEOUT:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nHALF:0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, True, False, 'Horizontal', '3,3,2,3;4,3,2,3;3,1,1,1;4,1,1,1;3;1,1,1,1;2,1,1,1', '0.2', False, True, True, 'Attention', False, False, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 3, 0, False, False, 0, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0, 'Blur First V1', 0.25, 10, 10, 10, 10, 1, False, '', '', 0.5, 1, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\SDwebui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\SDwebui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\SDwebui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\SDwebui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "C:\SDwebui\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\SDwebui\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\SDwebui\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SDwebui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "C:\SDwebui\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SDwebui\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\SDwebui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\modules\sd_samplers_kdiffusion.py", line 145, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\SDwebui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\SDwebui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\SDwebui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\SDwebui\python\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\SDwebui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "C:\SDwebui\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\SDwebui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 1067, in forward
    ox = matsepcalc(x, contexts, mask, self.pn, 1)
  File "C:\SDwebui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 931, in matsepcalc
    out = out.reshape(out.size()[0], dsh, dsw, out.size()[2]) # convert to main shape.
RuntimeError: shape '[1, 47, 32, 320]' is invalid for input of size 1845120
```

Could it be caused by my low VRAM?

**Comment by Sakura-Luna** [comment]
When I saw your prompt, I almost thought you were stress testing the extension.

Looks like a chunking bug. There is a suggestion, do not specify the size of the image too casually, if you use the slider, you will find that the resolution of the WebUI is fixed to be a multiple of 8, which can avoid some potential problems.

**Comment by NalihznehC** [comment]
> When I saw your prompt, I almost thought you were stress testing the extension.
> 
> Looks like a chunking bug. There is a suggestion, do not specify the size of the image too casually, if you use the slider, you will find that the resolution of the WebUI is fixed to be a multiple of 8, which can avoid some potential problems.

Thank you for the suggestion! 512x768 and even 560x840 are functional! 
Therefore, the real *problem* seems to be, In the current version, 
### when using this extension, dimensions must be set to multiples of 8.

**Comment by hako-mikan** [comment]
Values such as 510 are automatically converted to multiples of 8. Perhaps the size of the generated image is not 510.

**Comment by Symbiomatrix** [comment]
> ### when using this extension, dimensions must be set to multiples of 8.

Correct, that is one of the early fixes I submitted - it assumes that the model works by halving the height and width at every step and rounding up, which the interface seems to support. It was necessary in order to get all (feasible) combinations of base height & width, since working with the given reduced dimensions blindly and trying to figure out what the intended split is mathematically, proved to be difficult to impossible because of the cumulative rounding factor distorting the estimate.

Curious, how'd you force these nonstandard dimensions?

**Comment by Sakura-Luna** [comment]
> Curious, how'd you force these nonstandard dimensions?

The text box of WebUI accepts any size, and the unexpected size may not necessarily cause an error. Maybe it has something to do with too many sub-areas? Since it's expected behavior, there doesn't seem to be a need to modify it.

**Comment by Symbiomatrix** [comment]
@Sakura-Luna Thanks. Tested a bit, seems that for the sake of the model it simply rounds the height / width down to the nearest value divisible by 8. Easy fix, supporting it though nonstandard doesn't seem like a bad idea (though added a warning for it nevertheless). Tested on op's magnum opus prompt, looks perfectly fine.

**Comment by Morriaty-The-Murderer** [comment]
hi guys, is this fixed? I met the same error

regional prompter version: 2170e3c9 (Sun Apr 30 04:02:27 2023)

it failed when set origin resolution to 1024*1368 and upscale(txt2image Highres.fix) 1.5 times

it successed when set origin resolution to 768*1024 and upscale(txt2image Highres.fix) 2 times

**Comment by hako-mikan** [comment]
Fixed.

**Comment by T3chRomanc3r** [comment]
When Hires fix is enabled, I get
RuntimeError: shape '[1, 6, 11, 1280]' is invalid for input of size 143360

Divide Ratio is 1,1,1, prompt is simple and separated by three BREAKs

`Error completing request
Arguments: ('task(0ewmm3l06ylq2q3)', 'Astonishing studio food photography, <lora:foodPhotography_v10:0.3>,<lora:add_detail:1>, (to8contrast style:0.0) <lora:to8contrast-1-5:0.0>, bright morning sun,\nBottled maple syrup, clear glass transparent plate, caustics, bulky glass teapot with hot tea, water droplets\nBREAK\na pancake cake sandwich with raspberry jam, foodphoto, hot steamy pancakes, tasty\nBREAK\npool willed with water in Finish sauna', 'easynegative, (lr:1.3)', [], 30, 12, False, False, 1, 1, 7, 2431988250.0, -1.0, 0, 0, 0, False, 512, 864, True, 0.32, 1.5, '4x-UltraSharp', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, <controlnet.py.UiControlNetUnit object at 0x000002543463E860>, <controlnet.py.UiControlNetUnit object at 0x00000253885B4C70>, <controlnet.py.UiControlNetUnit object at 0x000002543463FE20>, <controlnet.py.UiControlNetUnit object at 0x00000253885B4910>, True, False, 'Horizontal', '1,1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\stable-diffusion-webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\stable-diffusion-webui\modules\processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\stable-diffusion-webui\modules\processing.py", line 907, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 154, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 799, in forward
    h = self.middle_block(h, emb, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward    x = layer(x, context)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 375, in forward
    ox = matsepcalc(x, contexts, mask, self.pn, 1)
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 184, in matsepcalc
    out = out.reshape(out.size()[0], dsh, dsw, out.size()[2]) # convert to main shape.
RuntimeError: shape '[1, 6, 11, 1280]' is invalid for input of size 143360`

**Comment by Symbiomatrix** [comment]
@T3chRomanc3r 
1) Please open a separate issue, this one's ancient and completely unrelated to yours.
2) I can't make anything out of the traceback, you have a bunch of extensions and the parameters are completely untagged there. Please clarify what out of the ordinary settings exactly you've used (description or screenshots will do) - specifically extensions enabled and dimension related settings.
