### ISSUE TITLE
Regional Prompter will not run even with Fresh Automatic1111 install

### ISSUE THREAD

**Issue by mvanzorn** [hako-mikan/sd-webui-regional-prompter#75]
Love the concept of regional prompter, but can't get it to run.

Windows 11, brand new install of Automatic1111, brand new install of sd-webui-regional-prompter using the UI.

Every time, the follow errors are thrown, and the regional prompter dialogue boxes do not appear.

Hoping you can help. Thanks!

ERRORS:

`Error calling: C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "C:\Users\me\stable-diffusion-webui\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "D:\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error calling: C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "C:\Users\me\stable-diffusion-webui\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "D:\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by mvanzorn** [comment]
Turns out that A1111's scripts directory had an empty  regional_prompter_presets.json file.
Added a pair of curly brackets, saved, and now the extension is running great. Thanks again for the excellent work.

**Comment by Symbiomatrix** [comment]
Thanks for bringing it up. Kinda bleeding edge yet a necessary restructure of the code, so feedback is important to iron out any bugs.
