### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by crazygonuts** [hako-mikan/sd-webui-regional-prompter#76]
I'm getting these errors in the cmd window on startup:

Error calling: C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error calling: C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I assume this is breaking the extension because I don't see the dropdown for it on the txt2img tab.

I'm getting this error in both automatic1111 and vladmandic fork

**Comment by crazygonuts** [comment]
found a reddit comment that fixed it for me:

https://www.reddit.com/r/StableDiffusion/comments/13360c1/comment/ji8ndi9/

the /scripts/regional_prompter_presets.json is a blank file and requires a pair of curly braces to be valid JSON

**Comment by Symbiomatrix** [comment]
Oh, it was empty? Odd, unless there was a write error it should've attempted to fill it with some predefined presets on first load via initpresets. I'll have a look.
