### ISSUE TITLE
Mask mode: TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by crazygonuts** [hako-mikan/sd-webui-regional-prompter#78]
Trying to use a mask I'm getting the error "TypeError: 'float' object is not subscriptable.  I'm providing screenshots of my settings, as well as the output when "debug" is checked

![promp_settings](https://user-images.githubusercontent.com/131223696/235336431-a80f9245-604a-4fe7-9234-d04bc25dd15e.PNG)
![regional_prompt_settings](https://user-images.githubusercontent.com/131223696/235336443-2561070e-4782-4185-a465-26e31c0dbf78.PNG)

pos tokens : [14, 22, 26], neg tokens : [23]
mode : Attention
divide : Mask
usebase : True
base ratios : [0.2]
usecommon : True
usenegcom : False
use 2D : False
divide : 0
eq : False

ratios : []

prompt : []

  0%|                                                                                           | 0/20 [00:00<?, ?it/s]input :  torch.Size([2, 9216, 320])
tokens :  torch.Size([2, 77, 768])
module :  diffusion_model_input_blocks_1_1_transformer_blocks_0_attn2
same token size and different divisions
3 96 96 9216 9216
tokens : [[0, 1], [1, 2], [2, 3]],pn : True
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(rakaub1to7bkji1)', "(best quality, masterpiece) BREAK two people standing across from each other BREAK warhammer 40k, space marine, red power armor, huge and imposing BREAK 1980's style cartoon anime schoolgirl in a school uniform looking annoying, tsundere", '(worst quality, low quality, easynegative, badhandv4)', [], 20, 15, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 768, 768, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, 'Send to Canvas Editor', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <controlnet.py.UiControlNetUnit object at 0x000001EA4DF9B850>, <controlnet.py.UiControlNetUnit object at 0x000001EA4DF7F100>, <controlnet.py.UiControlNetUnit object at 0x000001EA4DF7E6B0>, <controlnet.py.UiControlNetUnit object at 0x000001EA4DF7FA60>, True, True, 'Mask', '1,1', '0.2', True, True, False, 'Attention', False, '0', '0', '0.4', {'image': array([[[128,  64,  64],
        [128,  64,  64],
        [128,  64,  64],
        ...,
        [ 64, 128, 128],
        [ 64, 128, 128],
        [255, 255, 255]],

       [[128,  64,  64],
        [128,  64,  64],
        [128,  64,  64],
        ...,
        [ 64, 128, 128],
        [ 64, 128, 128],
        [255, 255, 255]],

       [[128,  64,  64],
        [128,  64,  64],
        [128,  64,  64],
        ...,
        [ 64, 128, 128],
        [ 64, 128, 128],
        [255, 255, 255]],

       ...,

       [[128,  64,  64],
        [128,  64,  64],
        [128,  64,  64],
        ...,
        [ 64, 128, 128],
        [ 64, 128, 128],
        [255, 255, 255]],

       [[128,  64,  64],
        [128,  64,  64],
        [128,  64,  64],
        ...,
        [ 64, 128, 128],
        [ 64, 128, 128],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 389, in forward
    opx = masksepcalc(px, conp, mask, True, 2)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 266, in masksepcalc
    bweight = self.bratios[0][i - 1]
TypeError: 'float' object is not subscriptable

**Comment by Symbiomatrix** [comment]
I think you did everything correctly. Reproduces on my end, will see what I can find.

**Comment by hako-mikan** [comment]
Its my mistake, when set base ratios for prompt mode.
I forgot to enable only prompt mode.

**Comment by crazygonuts** [comment]
thanks for the quick turnaround guys
