### ISSUE TITLE
Negative prompt error -- extension doesn't seem to work well with Torch2

### ISSUE THREAD

**Issue by lemimique** [hako-mikan/sd-webui-regional-prompter#85]
With the SD A1111 update today I'm getting this error:

`Error running process: D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 244, in process
    self, p = keydealer(self, p)
  File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 623, in keydealer
    if KEYCOMM in p.negtive_prompt:
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'negtive_prompt'`

It doesn't matter if I have checked the `Use negative prompt` option, it errors on or off.
The render goes on through though, although, I'm not sure if it uses the negative prompt.

Edit:
FYI: It seems a lot more stuff is broken now with regional-prompter A1111's SD WebUI has been updated to torch2. 

I can't get regions to work properly, and the error above is the only error I see. 

Edit 2:
[#rp.py#623](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/a3c22cedc3c66b89d995435f2d06baf2a86d6f51#diff-d8efbbc417b64113cc108d2f081a3840cfa4d8e1d66e18573d30d96a34f6b2f9R623)
I've locally fixed the typo. Errors are gone, but behaviour has not changed.

**Comment by crazygonuts** [comment]
Getting the same issue, i don't believe the extension is working when this happens although it can be difficult to tell
```

AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\StableDiffusion\vladmandic\modules\scripts.py:356 in process                                                     │
│                                                                                                                     │
│   355 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 356 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   357 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ C:\StableDiffusion\vladmandic\extensions\sd-webui-regional-prompter\scripts\rp.py:244 in process                    │
│                                                                                                                     │
│   243 │   │                                                                                                         │
│ > 244 │   │   self, p = keydealer(self, p)                                                                          │
│   245                                                                                                               │
│                                                                                                                     │
│ C:\StableDiffusion\vladmandic\extensions\sd-webui-regional-prompter\scripts\rp.py:623 in keydealer                  │
│                                                                                                                     │
│   622 │                                                                                                             │
│ > 623 │   if KEYCOMM in p.negtive_prompt:                                                                           │
│   624 │   │   self.usencom = True                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'negtive_prompt'
before_process_batch :  (best quality, masterpiece:1.4), ww2 news reel style, ADDCOMM mechanized combat ADDBASE a humanoid battlemech with cannon arms shooting ADDCOL ww2 german tank, tiger tank

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.72it/s]
postprocess_image :  0 0 (best quality, masterpiece:1.4), ww2 news reel style, ADDCOMM mechanized combat ADDBASE a humanoid battlemech with cannon arms shooting ADDCOL ww2 german tank, tiger tank
 ['(best quality, masterpiece:1.4), ww2 news reel style, ADDCOMM mechanized combat ADDBASE a humanoid battlemech with cannon arms shooting ADDCOL ww2 german tank, tiger tank\n']


```

**Comment by Symbiomatrix** [comment]
Ouch.

**Comment by Symbiomatrix** [comment]
Thanks @lemimique, @crazygonuts. Fixed the typo but I can't help for now.

**Comment by xueqing0622** [comment]
Fixed, Thanks
