### ISSUE TITLE
mask drawing help

### ISSUE THREAD

**Issue by Enferlain** [hako-mikan/sd-webui-regional-prompter#94]
Do I set the colors that are used for the masks like this?

![image](https://user-images.githubusercontent.com/15861396/235906106-63928a61-e955-487d-a413-cf751fb361d5.png)
![image](https://user-images.githubusercontent.com/15861396/235906164-a6a28e64-271a-4c11-85f9-cbff47b485b3.png)

**Comment by Enferlain** [comment]
![image](https://user-images.githubusercontent.com/15861396/235908945-1b066616-97ae-4891-82be-7532f9cc93f7.png)

sadge

**Comment by Enferlain** [comment]
Hmm. Any idea what this error is?

```
Error running process: /content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 267, in process
    self, p ,breaks = inpaintmaskdealer(self, p, bratios, usebase, polymask, comprompt, comnegprompt)
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/regions.py", line 647, in inpaintmaskdealer
    m = 1 - tm
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

```

This is the setup

![image](https://user-images.githubusercontent.com/15861396/235919216-78786714-6a4f-4509-b898-b179019cd3c2.png)

**Comment by Symbiomatrix** [comment]
Your colour choices seem correct. However, note that currently you must also tag each colour manually or in code - meaning, draw at least a single section (even if it falls within the existing mask and changes nothing) of each of colours you used in the mask, or add them to LCOLOURS. I believe this error indicates that LCOLOURS contains nothing.

Hopefully I can get around to improving this whole tedious upload process, plus the design for mask saving I have in mind, but might not happen till the weekend. Till then, if you can't figure out the upload, you can still draw the masks directly, I think the interface is not too unbearable for this purpose compared to standard image editors.

**Comment by Enferlain** [comment]
Ahhh, alright, thank you. I'll try it soon. The problem with directly drawing is that I have a depthmap for controlnet prepared and I'd need the masks to be drawn perfectly which sounds tough doing manually without having a layer to draw on top of. But I'll test it out without, maybe I can still build the image I want without controlnet

**Comment by Enferlain** [comment]
From the lora example on the page it seems like it can do alright with different loras in their region, but yeah I'll try next time and see how it goes.

**Comment by Symbiomatrix** [comment]
@Enferlain Once merged, the PR should fit your use case, I think. You can upload the depthmap as is to the inpaint+ area, then safely trace the regions you want to prompt for over it. You can save the completed mask to a preset. You can draw a mask with the hsv values externally as before and upload it, and it will handle the colour tagging.

**Comment by Enferlain** [comment]
Awesome, I'll test it out soon, thanks!
